//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_OPCIONES
    {
        public decimal OPC_ID { get; set; }
        public string OPC_DESCRIPCION { get; set; }
        public string OPC_TITULO { get; set; }
        public string OPC_SUBTITULO { get; set; }
        public Nullable<short> OPC_ID_PADRE { get; set; }
        public string OPC_ALT { get; set; }
        public string OPC_IMAGEN { get; set; }
        public string OPC_ACTIVO { get; set; }
        public byte OPC_NIVEL { get; set; }
        public string OPC_URL { get; set; }
        public Nullable<short> OPC_SECUENCIA { get; set; }
        public string OPC_TIPO { get; set; }
        public string OPC_URL_ACCIONES { get; set; }
        public Nullable<decimal> SER_ID { get; set; }
        public string OPC_MOSTRAR_ENMENU { get; set; }
        public string OPC_ARCHIVO_INSTRUCTIVO { get; set; }
        public Nullable<decimal> OPC_ID_RELACIONADA { get; set; }
    }
}
