//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_USUARIOS
    {
        public ADM_USUARIOS()
        {
            this.ART_ME_SOLICITUDES_COMENTARIOS = new HashSet<ART_ME_SOLICITUDES_COMENTARIOS>();
            this.ART_MUSICA_ENTIDAD_IDENTIFICACION = new HashSet<ART_MUSICA_ENTIDAD_IDENTIFICACION>();
        }
    
        public decimal USU_ID { get; set; }
        public Nullable<decimal> ARE_ID { get; set; }
        public Nullable<decimal> SEC_ID { get; set; }
        public Nullable<decimal> DEP_ID { get; set; }
        public string USU_TIPO { get; set; }
        public string USU_USUARIO { get; set; }
        public string USU_NOMBRE { get; set; }
        public string USU_CARGO { get; set; }
        public string USU_DIRECCION { get; set; }
        public string USU_TELEFONO { get; set; }
        public string USU_CORREO_ELECTRONICO { get; set; }
        public int USU_DIAS_EXPIRACION { get; set; }
        public string USU_CLAVE { get; set; }
        public string USU_CAMBIO_CLAVE { get; set; }
        public Nullable<System.DateTime> USU_FECHA_ULTIMO_INGRESO { get; set; }
        public Nullable<System.DateTime> USU_FECHA_CAMBIO_CLAVE { get; set; }
        public Nullable<System.DateTime> USU_FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> USU_FECHA_ACTUALIZACION { get; set; }
        public string USU_ESTADO { get; set; }
        public Nullable<int> USU_INTENTOS_FALLIDOS_INGRESO { get; set; }
        public string USU_ADMINISTRADOR { get; set; }
        public string USU_REVISOR_ESTILO { get; set; }
        public string ZON_ID { get; set; }
        public string USU_DEPARTAMENTO { get; set; }
        public Nullable<decimal> usu_id_anterior { get; set; }
        public string USU_NIT { get; set; }
        public string USU_RECIBIR_INFO_TEMAS_INTERES { get; set; }
        public string USU_GENERO { get; set; }
        public Nullable<System.DateTime> USU_FECHA_NACIMIENTO { get; set; }
        public string USU_ACTIVIDAD_RELACIONADA_CULTURA { get; set; }
        public Nullable<int> ZOP_ID { get; set; }
        public Nullable<bool> ES_PRIMER_ENTRADA { get; set; }
    
        public virtual ICollection<ART_ME_SOLICITUDES_COMENTARIOS> ART_ME_SOLICITUDES_COMENTARIOS { get; set; }
        public virtual ART_ME_USUARIOS ART_ME_USUARIOS { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDAD_IDENTIFICACION> ART_MUSICA_ENTIDAD_IDENTIFICACION { get; set; }
    }
}
