//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_TRADICIONAL_AUDIOS
    {
        public int Id { get; set; }
        public int GeneroId { get; set; }
        public string Titulo { get; set; }
        public string Detalle { get; set; }
        public string NombreArchivo { get; set; }
        public string Ruta { get; set; }
        public bool EstadoId { get; set; }
    
        public virtual ART_MUSICA_TRADICIONAL_GENEROS ART_MUSICA_TRADICIONAL_GENEROS { get; set; }
    }
}
