//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_FORMACION_PRACTICA
    {
        public ART_MUSICA_FORMACION_PRACTICA()
        {
            this.ART_MUSICA_PRACTICA_GENERO = new HashSet<ART_MUSICA_PRACTICA_GENERO>();
            this.ART_MUSICA_PRACTICA_NIVEL = new HashSet<ART_MUSICA_PRACTICA_NIVEL>();
        }
    
        public int Id { get; set; }
        public decimal EscuelaId { get; set; }
        public short PracticaMusicalId { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ART_MUSICA_PRACTICA_MUSICAL ART_MUSICA_PRACTICA_MUSICAL { get; set; }
        public virtual ICollection<ART_MUSICA_PRACTICA_GENERO> ART_MUSICA_PRACTICA_GENERO { get; set; }
        public virtual ICollection<ART_MUSICA_PRACTICA_NIVEL> ART_MUSICA_PRACTICA_NIVEL { get; set; }
    }
}
