//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_FORMULARIOS_SECCIONES
    {
        public ART_ME_FORMULARIOS_SECCIONES()
        {
            this.ART_ME_FORMULARIOS_COLUMNAS = new HashSet<ART_ME_FORMULARIOS_COLUMNAS>();
        }
    
        public decimal FSC_ID { get; set; }
        public string FSC_NOMBRE { get; set; }
        public int FSC_DUPLICACIONES { get; set; }
        public decimal FOR_ID { get; set; }
    
        public virtual ART_ME_FORMULARIOS ART_ME_FORMULARIOS { get; set; }
        public virtual ICollection<ART_ME_FORMULARIOS_COLUMNAS> ART_ME_FORMULARIOS_COLUMNAS { get; set; }
    }
}
