//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_AGENTE_INTERESES
    {
        public int Id { get; set; }
        public int AgenteId { get; set; }
        public Nullable<int> InteresesId { get; set; }
        public string Atributo { get; set; }
        public string Estado { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ART_MUSICA_INTERESES ART_MUSICA_INTERESES { get; set; }
    }
}
