//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_REGION_OCAD
    {
        public ART_MUS_FESTIVALES_REGION_OCAD()
        {
            this.ART_MUS_ZONAXREGION_OCAD = new HashSet<ART_MUS_ZONAXREGION_OCAD>();
        }
    
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<ART_MUS_ZONAXREGION_OCAD> ART_MUS_ZONAXREGION_OCAD { get; set; }
    }
}
