//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_AGENTE_EXPERIENCIA
    {
        public int Id { get; set; }
        public int AgenteId { get; set; }
        public string Empresa { get; set; }
        public string Titulo { get; set; }
        public int MesInicio { get; set; }
        public int AnoInicio { get; set; }
        public Nullable<int> MesFin { get; set; }
        public Nullable<int> AnoFin { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> TrabajoActual { get; set; }
        public int Tipo { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
    }
}
