//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_FORMULARIOS
    {
        public ART_ME_FORMULARIOS()
        {
            this.ART_ME_FORMULARIOS_COLUMNAS = new HashSet<ART_ME_FORMULARIOS_COLUMNAS>();
            this.ART_ME_FORMULARIOS_SECCIONES = new HashSet<ART_ME_FORMULARIOS_SECCIONES>();
            this.ART_ME_FORMULARIOS_VALORES = new HashSet<ART_ME_FORMULARIOS_VALORES>();
            this.ART_MUSICA_FORMULARIO_ARCHIVOS = new HashSet<ART_MUSICA_FORMULARIO_ARCHIVOS>();
        }
    
        public decimal FOR_ID { get; set; }
        public string FOR_NOMBRE { get; set; }
        public string FOR_DESCRIPCION { get; set; }
        public string FOR_ESACTIVA { get; set; }
        public System.DateTime FOR_FECHA_REGISTRO { get; set; }
        public string FOR_ESVISIBLE { get; set; }
        public string FOR_ESEDITABLE { get; set; }
        public string FOR_PERFILES { get; set; }
    
        public virtual ICollection<ART_ME_FORMULARIOS_COLUMNAS> ART_ME_FORMULARIOS_COLUMNAS { get; set; }
        public virtual ICollection<ART_ME_FORMULARIOS_SECCIONES> ART_ME_FORMULARIOS_SECCIONES { get; set; }
        public virtual ICollection<ART_ME_FORMULARIOS_VALORES> ART_ME_FORMULARIOS_VALORES { get; set; }
        public virtual ICollection<ART_MUSICA_FORMULARIO_ARCHIVOS> ART_MUSICA_FORMULARIO_ARCHIVOS { get; set; }
    }
}
