//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_ZONAXREGION_OCAD
    {
        public int ID { get; set; }
        public string ZON_ID { get; set; }
        public int REGION_OCAD_ID { get; set; }
    
        public virtual ART_MUS_FESTIVALES_REGION_OCAD ART_MUS_FESTIVALES_REGION_OCAD { get; set; }
        public virtual BAS_ZONAS_GEOGRAFICAS BAS_ZONAS_GEOGRAFICAS { get; set; }
    }
}
