//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_SOLICITUD_USUARIOS
    {
        public int Id { get; set; }
        public Nullable<int> EscuelaId { get; set; }
        public int UsuarioId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<int> UsuarioAprobador { get; set; }
        public string CodMunicipio { get; set; }
        public Nullable<int> EventoId { get; set; }
    
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
    }
}
