//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_CONVENIOS
    {
        public ART_MUSICA_CONVENIOS()
        {
            this.ART_MUSICA_AGENTEXCONVENIO = new HashSet<ART_MUSICA_AGENTEXCONVENIO>();
            this.ART_MUSICA_ACTIVIDADES = new HashSet<ART_MUSICA_ACTIVIDADES>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Objeto { get; set; }
        public decimal Valor { get; set; }
        public int EntidadId { get; set; }
        public int Coord_AgenteId { get; set; }
        public int Periodo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int EstadoId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> DocumentoId { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTEXCONVENIO> ART_MUSICA_AGENTEXCONVENIO { get; set; }
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_ACTIVIDADES> ART_MUSICA_ACTIVIDADES { get; set; }
        public virtual ART_MUSICA_DOCUMENTOS ART_MUSICA_DOCUMENTOS { get; set; }
    }
}
