//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_FUENTE_FINANCIACION
    {
        public ART_MUS_FESTIVALES_FUENTE_FINANCIACION()
        {
            this.ART_MUS_FESTIVALES_VERSION = new HashSet<ART_MUS_FESTIVALES_VERSION>();
            this.ART_MUS_FESTIVALES_VERSION1 = new HashSet<ART_MUS_FESTIVALES_VERSION>();
        }
    
        public int ID { get; set; }
        public string FUENTE_FINANCIACION { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual ICollection<ART_MUS_FESTIVALES_VERSION> ART_MUS_FESTIVALES_VERSION { get; set; }
        public virtual ICollection<ART_MUS_FESTIVALES_VERSION> ART_MUS_FESTIVALES_VERSION1 { get; set; }
    }
}
