//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ENTIDADES_ARTES
    {
        public ART_ENTIDADES_ARTES()
        {
            this.ART_INFRAESTRUCTURA_ENTIDADES = new HashSet<ART_INFRAESTRUCTURA_ENTIDADES>();
            this.ART_ME_IMAGENES_ESCUELAS = new HashSet<ART_ME_IMAGENES_ESCUELAS>();
            this.ART_ME_VIDEOS_ESCUELAS = new HashSet<ART_ME_VIDEOS_ESCUELAS>();
            this.ART_MUSICA_ENTIDAD_CATEGORIZACION = new HashSet<ART_MUSICA_ENTIDAD_CATEGORIZACION>();
            this.ART_MUSICA_ENTIDAD_TIPOS_INTERNET = new HashSet<ART_MUSICA_ENTIDAD_TIPOS_INTERNET>();
            this.ART_MUSICA_ESCUELAS_DOCUMENTOS = new HashSet<ART_MUSICA_ESCUELAS_DOCUMENTOS>();
            this.ART_MUSICA_PRACTICAS_PNMC = new HashSet<ART_MUSICA_PRACTICAS_PNMC>();
            this.ART_MUSICA_FORMACION_PRACTICA = new HashSet<ART_MUSICA_FORMACION_PRACTICA>();
            this.ART_MUSICA_PRACTICA_NIVEL = new HashSet<ART_MUSICA_PRACTICA_NIVEL>();
            this.ART_MUSICA_ESCUELA_ASESORIA = new HashSet<ART_MUSICA_ESCUELA_ASESORIA>();
            this.ART_MUSICA_ESCUELA_CLASIFICACION = new HashSet<ART_MUSICA_ESCUELA_CLASIFICACION>();
            this.ART_MUSICA_ESCUELA_MATRIZ = new HashSet<ART_MUSICA_ESCUELA_MATRIZ>();
            this.ART_MUSICA_ESCUELA_OBSERVACION = new HashSet<ART_MUSICA_ESCUELA_OBSERVACION>();
            this.ART_MUSICA_MOTIVO_HISTORICO = new HashSet<ART_MUSICA_MOTIVO_HISTORICO>();
            this.ART_MUSICA_ESCUELA_INSTRUMENTOS = new HashSet<ART_MUSICA_ESCUELA_INSTRUMENTOS>();
        }
    
        public decimal ENT_ID { get; set; }
        public decimal DOC_ID_REPRESENTANTE { get; set; }
        public Nullable<decimal> DOC_ID_ENTIDAD { get; set; }
        public System.DateTime ENT_FECHA_DILIGENCIAMIENTO { get; set; }
        public string ENT_RUT { get; set; }
        public Nullable<decimal> ATP_ID { get; set; }
        public string ENT_OTRA_CLASE_ENTIDAD { get; set; }
        public Nullable<int> ENT_FORMACION_PRACTICAS_ARTISTICAS { get; set; }
        public Nullable<int> ENT_NRO_INTEGRANTES_PRACTICAS { get; set; }
        public string ENT_FORMACION_PUBLICO { get; set; }
        public string ENT_NUM_DOCUMENTO_REPRESENTANTE { get; set; }
        public string ENT_NOMBRE { get; set; }
        public string ENT_IMAGEN { get; set; }
        public string ENT_PAGINA_WEB { get; set; }
        public string ENT_ESTADO { get; set; }
        public Nullable<System.DateTime> ENT_FECHA_VIGENCIA_INICIAL { get; set; }
        public Nullable<System.DateTime> ENT_FECHA_VIGENCIA_FINAL { get; set; }
        public string ENT_NIT { get; set; }
        public Nullable<int> ENT_ANO_CONSTITUCION { get; set; }
        public Nullable<decimal> ENT_ACTIVIDAD_PRINCIPAL { get; set; }
        public Nullable<decimal> ENT_AREA_ARTISTICA { get; set; }
        public string ENT_NOMBRE_REPRESENTANTE_LEGAL { get; set; }
        public string ENT_CARGO_REPRESENTANTE_LEGAL { get; set; }
        public Nullable<int> ENT_ANO_VINCUALCION_REPRESENTANTE_LEGAL { get; set; }
        public string ENT_NOMBRE_CONTACTO { get; set; }
        public string ENT_CARGO_CONTACTO { get; set; }
        public Nullable<int> ENT_ANO_VINCUALCION_CONTACTO { get; set; }
        public Nullable<int> ENT_NIVEL_ENTIDAD_DEPENDE_RED { get; set; }
        public string ENT_NOMBRE_ENTIDAD_DEPENDE_RED { get; set; }
        public string ENT_OBSERVACION_VALIDACION { get; set; }
        public string ENT_CONCERTACION { get; set; }
        public Nullable<System.DateTime> ENT_FECHA_ACTUALIZACION { get; set; }
        public Nullable<short> ENT_RECURSO_PRIVADO { get; set; }
        public Nullable<short> ENT_RECURSO_PUBLICO { get; set; }
        public Nullable<short> ENT_RECURSO_MIXTAS { get; set; }
        public Nullable<decimal> REG_ID { get; set; }
        public string ENT_LUGAR_EXPEDICION { get; set; }
        public string ENT_OTRO_NIVEL_FORMACION_IMPARTE { get; set; }
        public string ENT_EXPERIENCIA_EXITOSA { get; set; }
        public string ENT_RESENA { get; set; }
        public Nullable<System.DateTime> ENT_FECHA_CAMBIO_ESTADO { get; set; }
        public string ENT_OTROS_GENEROS { get; set; }
        public string ENT_ACTIVIDAD_PRINCIPAL_PRODUCTOR { get; set; }
        public Nullable<decimal> ENT_USU_VALIDA { get; set; }
        public string ENT_NUMERO_REGISTRO_PRODUCTOR { get; set; }
        public Nullable<decimal> ARD_ID { get; set; }
        public Nullable<decimal> ENT_ESTADO_LEP { get; set; }
        public string ENT_TIPO { get; set; }
        public Nullable<decimal> ent_id_anterior { get; set; }
        public Nullable<decimal> ATA_ID { get; set; }
    
        public virtual ART_ENTIDAD_UBICACION ART_ENTIDAD_UBICACION { get; set; }
        public virtual ART_MUSICA_ENTIDAD_FORMACION ART_MUSICA_ENTIDAD_FORMACION { get; set; }
        public virtual ART_MUSICA_ENTIDAD_INFRAESTRUCTURA ART_MUSICA_ENTIDAD_INFRAESTRUCTURA { get; set; }
        public virtual ART_MUSICA_ENTIDAD_PARTICIPACION ART_MUSICA_ENTIDAD_PARTICIPACION { get; set; }
        public virtual ART_MUSICA_ENTIDAD_PRODUCCION ART_MUSICA_ENTIDAD_PRODUCCION { get; set; }
        public virtual ICollection<ART_INFRAESTRUCTURA_ENTIDADES> ART_INFRAESTRUCTURA_ENTIDADES { get; set; }
        public virtual ICollection<ART_ME_IMAGENES_ESCUELAS> ART_ME_IMAGENES_ESCUELAS { get; set; }
        public virtual ICollection<ART_ME_VIDEOS_ESCUELAS> ART_ME_VIDEOS_ESCUELAS { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDAD_CATEGORIZACION> ART_MUSICA_ENTIDAD_CATEGORIZACION { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDAD_TIPOS_INTERNET> ART_MUSICA_ENTIDAD_TIPOS_INTERNET { get; set; }
        public virtual BAS_TIPOS_DOCUMENTOS_IDENTIDAD BAS_TIPOS_DOCUMENTOS_IDENTIDAD { get; set; }
        public virtual ART_ENTIDAD_NATURALEZA_JURIDICA ART_ENTIDAD_NATURALEZA_JURIDICA { get; set; }
        public virtual ART_MUSICA_ENTIDAD_IDENTIFICACION ART_MUSICA_ENTIDAD_IDENTIFICACION { get; set; }
        public virtual ICollection<ART_MUSICA_ESCUELAS_DOCUMENTOS> ART_MUSICA_ESCUELAS_DOCUMENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_PRACTICAS_PNMC> ART_MUSICA_PRACTICAS_PNMC { get; set; }
        public virtual ICollection<ART_MUSICA_FORMACION_PRACTICA> ART_MUSICA_FORMACION_PRACTICA { get; set; }
        public virtual ICollection<ART_MUSICA_PRACTICA_NIVEL> ART_MUSICA_PRACTICA_NIVEL { get; set; }
        public virtual ICollection<ART_MUSICA_ESCUELA_ASESORIA> ART_MUSICA_ESCUELA_ASESORIA { get; set; }
        public virtual ICollection<ART_MUSICA_ESCUELA_CLASIFICACION> ART_MUSICA_ESCUELA_CLASIFICACION { get; set; }
        public virtual ICollection<ART_MUSICA_ESCUELA_MATRIZ> ART_MUSICA_ESCUELA_MATRIZ { get; set; }
        public virtual ICollection<ART_MUSICA_ESCUELA_OBSERVACION> ART_MUSICA_ESCUELA_OBSERVACION { get; set; }
        public virtual ICollection<ART_MUSICA_MOTIVO_HISTORICO> ART_MUSICA_MOTIVO_HISTORICO { get; set; }
        public virtual ART_MUSICA_ENTIDAD_INSTITUCIONALIDAD ART_MUSICA_ENTIDAD_INSTITUCIONALIDAD { get; set; }
        public virtual ICollection<ART_MUSICA_ESCUELA_INSTRUMENTOS> ART_MUSICA_ESCUELA_INSTRUMENTOS { get; set; }
    }
}
