//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_HISTORICO_ESCUELAS
    {
        public int Id { get; set; }
        public int Periodo { get; set; }
        public Nullable<decimal> EscuelaId { get; set; }
        public string Nombre { get; set; }
        public string Naturaleza { get; set; }
        public string Departamento { get; set; }
        public string CodDepto { get; set; }
        public string Municipio { get; set; }
        public string CodMunicipio { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Legalmente { get; set; }
        public Nullable<int> TipoEscuelaId { get; set; }
        public Nullable<int> CuerdasPulsadas { get; set; }
        public Nullable<int> CuerdasSinfonicas { get; set; }
        public Nullable<int> OtrosInstrumentos { get; set; }
        public Nullable<int> PercusionMenor { get; set; }
        public Nullable<int> PercusionSinfonica { get; set; }
        public Nullable<int> Vientosmaderas { get; set; }
        public Nullable<int> VientosMetales { get; set; }
        public Nullable<int> Bandas { get; set; }
        public Nullable<int> Coros { get; set; }
        public Nullable<int> Iniciacion { get; set; }
        public Nullable<int> Tradicional { get; set; }
        public Nullable<int> Orquesta { get; set; }
        public Nullable<int> Urbana { get; set; }
        public Nullable<bool> DependeOtraEntidad { get; set; }
        public Nullable<bool> OrganizacionComunitaria { get; set; }
        public Nullable<int> Menor6 { get; set; }
        public Nullable<int> Entre7y11 { get; set; }
        public Nullable<int> Entre12y18 { get; set; }
        public Nullable<int> Entre19y25 { get; set; }
        public Nullable<int> Entre26y60 { get; set; }
        public Nullable<int> Mayor60 { get; set; }
        public Nullable<int> PoblacionUrbana { get; set; }
        public Nullable<int> PoblacionRural { get; set; }
        public Nullable<int> PoblacionFemenino { get; set; }
        public Nullable<int> PoblacionMasculino { get; set; }
        public Nullable<int> PoblacionAfro { get; set; }
        public Nullable<int> PoblacionRom { get; set; }
        public Nullable<int> PoblacionRaizales { get; set; }
        public Nullable<int> PoblacionIndigena { get; set; }
        public Nullable<int> PrimariaDocentes { get; set; }
        public Nullable<int> SecundariaDocentes { get; set; }
        public Nullable<int> TecnicoDocentes { get; set; }
        public Nullable<int> Universitario { get; set; }
        public Nullable<int> PregradoMusica { get; set; }
        public Nullable<int> PregradoOtro { get; set; }
        public Nullable<int> Posgrado { get; set; }
        public Nullable<int> Locales { get; set; }
        public Nullable<int> Nacionales { get; set; }
        public Nullable<int> Internacionales { get; set; }
        public string TipoEscuela { get; set; }
    }
}
