//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_ENTIDADES_ALIADAS
    {
        public int ID { get; set; }
        public string NOMBRE_ENTIDAD_ALIADA { get; set; }
        public Nullable<int> ID_NATURALEZA { get; set; }
        public Nullable<int> ID_FESTIVAL { get; set; }
        public string CORREO_ENTIDAD { get; set; }
    
        public virtual ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD { get; set; }
        public virtual ART_MUS_FESTIVALES_VERSION ART_MUS_FESTIVALES_VERSION { get; set; }
    }
}
