//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_HERRAMIENTAS
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int TipoId { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public string UrlArchivo { get; set; }
        public string UrlVideo { get; set; }
        public string Descripcion { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> UsuarioAprobadorId { get; set; }
        public string autores { get; set; }
    
        public virtual ART_MUSICA_DOCUMENTOS ART_MUSICA_DOCUMENTOS { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
    }
}
