//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_PERFILES
    {
        public ART_ME_PERFILES()
        {
            this.BAS_ZONAS_GEOGRAFICAS = new HashSet<BAS_ZONAS_GEOGRAFICAS>();
        }
    
        public decimal PER_SIPA_ID { get; set; }
        public string PER_ESTADO_ME { get; set; }
        public string PER_TIPO_ME { get; set; }
        public string PER_EDITAR_ESCUELA { get; set; }
        public string PER_PUBLICAR_ESCUELA { get; set; }
        public string PER_CREAR_SOLICITUD { get; set; }
    
        public virtual ICollection<BAS_ZONAS_GEOGRAFICAS> BAS_ZONAS_GEOGRAFICAS { get; set; }
    }
}
