//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_CELEBRA_CATEGORIA
    {
        public ART_MUSICA_CELEBRA_CATEGORIA()
        {
            this.ART_MUSICA_ARTISTAS_CELEBRA = new HashSet<ART_MUSICA_ARTISTAS_CELEBRA>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual ICollection<ART_MUSICA_ARTISTAS_CELEBRA> ART_MUSICA_ARTISTAS_CELEBRA { get; set; }
    }
}
