//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_RED_SOCIAL_ESCENARIOS
    {
        public int Id { get; set; }
        public Nullable<int> EventoPeriodicoId { get; set; }
        public Nullable<int> EscenarioId { get; set; }
        public string Valor { get; set; }
    
        public virtual ART_MUSICA_EVENTOS_PERIODICOS ART_MUSICA_EVENTOS_PERIODICOS { get; set; }
        public virtual ART_MUSICA_ESCENARIOS ART_MUSICA_ESCENARIOS { get; set; }
    }
}
