//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_LOCALIZACIONXVERSION
    {
        public int ID { get; set; }
        public int ID_VERSION { get; set; }
        public string ZON_ID { get; set; }
        public Nullable<int> ID_ZONA { get; set; }
        public Nullable<int> ID_TITULACION_COLECTIVA { get; set; }
    
        public virtual ART_MUS_FESTIVALES_VERSION ART_MUS_FESTIVALES_VERSION { get; set; }
        public virtual ART_MUS_FESTIVALES_ZONA ART_MUS_FESTIVALES_ZONA { get; set; }
        public virtual ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA { get; set; }
        public virtual BAS_ZONAS_GEOGRAFICAS BAS_ZONAS_GEOGRAFICAS { get; set; }
    }
}
