//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ORGANIZACION_COMUNITARIA
    {
        public ART_MUSICA_ORGANIZACION_COMUNITARIA()
        {
            this.ART_MUSICA_ENTIDAD_PARTICIPACION = new HashSet<ART_MUSICA_ENTIDAD_PARTICIPACION>();
        }
    
        public short ORGANIZACION_COMUNITARIA_ID { get; set; }
        public string ORGANIZACION_COMUNITARIA_DESCRIPCION { get; set; }
    
        public virtual ICollection<ART_MUSICA_ENTIDAD_PARTICIPACION> ART_MUSICA_ENTIDAD_PARTICIPACION { get; set; }
    }
}
