//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_PROCESOS
    {
        public ART_MUSICA_PROCESOS()
        {
            this.ART_MUSICA_OFICIOS = new HashSet<ART_MUSICA_OFICIOS>();
            this.ART_MUSICA_INTERESES = new HashSet<ART_MUSICA_INTERESES>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> PadreId { get; set; }
    
        public virtual ICollection<ART_MUSICA_OFICIOS> ART_MUSICA_OFICIOS { get; set; }
        public virtual ICollection<ART_MUSICA_INTERESES> ART_MUSICA_INTERESES { get; set; }
    }
}
