//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ENTIDAD_UBICACION
    {
        public decimal ENT_ID { get; set; }
        public int ZOP_ID { get; set; }
        public string ZON_ID { get; set; }
        public decimal ARE_ID { get; set; }
        public string ENT_DIRECCION { get; set; }
        public string ENT_DIRECCION_CORRESPONDENCIA { get; set; }
        public string ENT_SINO_TELEFONO { get; set; }
        public string ENT_TELEFONO { get; set; }
        public string ENT_SINO_FAX { get; set; }
        public string ENT_FAX { get; set; }
        public string ENT_APARTADO_AEREO { get; set; }
        public string ENT_SINO_CORREO_ELECTRONICO_ENTIDAD { get; set; }
        public string ENT_CORREO_ELECTRONICO_ENTIDAD { get; set; }
        public string ENT_PAGINA_WEB { get; set; }
        public string ENT_CIUDAD { get; set; }
        public string ENT_DIRTRAD { get; set; }
        public Nullable<double> ENT_LATITUD { get; set; }
        public Nullable<double> ENT_LONGITUD { get; set; }
        public string ENT_ESTADO_GEO { get; set; }
        public string PERFIL_FACEBOOK { get; set; }
        public string PERFIL_TWITTER { get; set; }
        public string CANAL_YOUTUBE { get; set; }
        public string ENT_CORREO_ELECTRONICO_REPRE_LEGAL { get; set; }
        public Nullable<double> MUS_LATITUD { get; set; }
        public Nullable<double> MUS_LONGITUD { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual BAS_ZONAS_GEOGRAFICAS BAS_ZONAS_GEOGRAFICAS { get; set; }
        public virtual BAS_ZONAS_PAISES BAS_ZONAS_PAISES { get; set; }
    }
}
