//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_FORMULARIOS_VALORES
    {
        public decimal FVA_ID { get; set; }
        public string FVA_VALOR { get; set; }
        public decimal FCO_ID { get; set; }
        public decimal FRE_ID { get; set; }
        public decimal FOR_ID { get; set; }
        public Nullable<int> FVA_DUPLICACION { get; set; }
    
        public virtual ART_ME_FORMULARIOS ART_ME_FORMULARIOS { get; set; }
        public virtual ART_ME_FORMULARIOS_COLUMNAS ART_ME_FORMULARIOS_COLUMNAS { get; set; }
        public virtual ART_ME_FORMULARIOS_REGISTRO ART_ME_FORMULARIOS_REGISTRO { get; set; }
    }
}
