//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_TIP_DOC_CRE_ENT_INSTITUC
    {
        public decimal ENT_ID { get; set; }
        public short ART_MUS_TIP_DOC_CRE_ID { get; set; }
        public string ART_MUS_TIP_DOC_CRE_DOCUMENTO { get; set; }
        public string ART_MUS_TIP_DOC_CRE_NUMERO_DOC { get; set; }
        public System.DateTime ART_MUS_TIP_DOC_CRE_FECHA_DOC { get; set; }
        public Nullable<int> DocumentoId { get; set; }
    
        public virtual ART_MUSICA_TIPO_DOCUMENTO_CREACION ART_MUSICA_TIPO_DOCUMENTO_CREACION { get; set; }
        public virtual ART_MUSICA_ENTIDAD_INSTITUCIONALIDAD ART_MUSICA_ENTIDAD_INSTITUCIONALIDAD { get; set; }
    }
}
