//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_CONVENIO_DOTACION
    {
        public int Id { get; set; }
        public int TipoId { get; set; }
        public int ElementoId { get; set; }
        public int FormatoId { get; set; }
        public string Marca { get; set; }
        public string Referencia { get; set; }
        public string Serial { get; set; }
        public string Garantia { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public int CronogramaId { get; set; }
        public string Prooveedor { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ART_MUSICA_CRONOGRAMA ART_MUSICA_CRONOGRAMA { get; set; }
    }
}
