//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_FACTOR_CATEGORIZACION
    {
        public ART_MUSICA_FACTOR_CATEGORIZACION()
        {
            this.ART_MUSICA_FACTOR_CATEGORIZACION1 = new HashSet<ART_MUSICA_FACTOR_CATEGORIZACION>();
        }
    
        public int ID_FACTOR { get; set; }
        public string DESCRIPCION_FACTOR { get; set; }
        public Nullable<int> ID_FACTOR_PADRE { get; set; }
        public decimal PORCENTAJE_FACTOR { get; set; }
        public string CONSULTA { get; set; }
        public Nullable<short> ID_TIPO_DATO_RETORNO { get; set; }
    
        public virtual ART_MUSICA_TIPO_DATO_RETORNO ART_MUSICA_TIPO_DATO_RETORNO { get; set; }
        public virtual ICollection<ART_MUSICA_FACTOR_CATEGORIZACION> ART_MUSICA_FACTOR_CATEGORIZACION1 { get; set; }
        public virtual ART_MUSICA_FACTOR_CATEGORIZACION ART_MUSICA_FACTOR_CATEGORIZACION2 { get; set; }
    }
}
