//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ENTIDAD_DOTACION
    {
        public int Id { get; set; }
        public int EntidadId { get; set; }
        public int ConvocatoriaId { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual ART_MUSICA_CONVOCATORIAS ART_MUSICA_CONVOCATORIAS { get; set; }
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES { get; set; }
    }
}
