//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_USUARIO_ROL
    {
        public int Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ART_MUSICA_ROL ART_MUSICA_ROL { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
    }
}
