//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ESCENARIOS
    {
        public ART_MUSICA_ESCENARIOS()
        {
            this.ART_MUSICA_ESCENARIO_DIAS = new HashSet<ART_MUSICA_ESCENARIO_DIAS>();
            this.ART_MUSICA_RED_SOCIAL_ESCENARIOS = new HashSet<ART_MUSICA_RED_SOCIAL_ESCENARIOS>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string CodDepto { get; set; }
        public string Departamento { get; set; }
        public string CodMunicipio { get; set; }
        public string Municipio { get; set; }
        public string Direccion { get; set; }
        public int Aforo { get; set; }
        public string RelacionadoA { get; set; }
        public Nullable<int> AgrupacionId { get; set; }
        public Nullable<decimal> EscuelaId { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public string NombreActor { get; set; }
        public string PaginaWeb { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public string Contacto { get; set; }
        public int EstadoId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public string Descripcion { get; set; }
        public int ClasificacionId { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> TipoActor { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFinal { get; set; }
        public Nullable<int> UsuarioActualizaId { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ART_MUSICA_AGRUPACION ART_MUSICA_AGRUPACION { get; set; }
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES { get; set; }
        public virtual ICollection<ART_MUSICA_ESCENARIO_DIAS> ART_MUSICA_ESCENARIO_DIAS { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_RED_SOCIAL_ESCENARIOS> ART_MUSICA_RED_SOCIAL_ESCENARIOS { get; set; }
    }
}
