//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ENTIDAD_IDENTIFICACION
    {
        public decimal ENT_ID { get; set; }
        public string ENT_TELEFONOS { get; set; }
        public string ENT_CONTACTO_CORREO { get; set; }
        public Nullable<decimal> USU_ID { get; set; }
        public Nullable<decimal> USU_ID_ANTERIOR { get; set; }
        public byte[] Imagen { get; set; }
        public string ENT_TIPO_ESCUELA { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> OperatividadId { get; set; }
    
        public virtual ADM_USUARIOS ADM_USUARIOS { get; set; }
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
    }
}
