//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION
    {
        public ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION()
        {
            this.ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION = new HashSet<ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION>();
        }
    
        public int ID { get; set; }
        public string MODALIDAD_PARTICIPACION { get; set; }
        public int ACTIVO { get; set; }
    
        public virtual ICollection<ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION> ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION { get; set; }
    }
}
