//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_SOLICITUDES_COMENTARIOS
    {
        public decimal SCO_ID { get; set; }
        public decimal SCO_SOLICITUD_ID { get; set; }
        public string SCO_COMENTARIO { get; set; }
        public string SCO_ARCHIVO { get; set; }
        public decimal SCO_AUTOR_ID { get; set; }
        public System.DateTime SCO_FECHA_REGISTRO { get; set; }
        public string SCO_RESPUESTA { get; set; }
    
        public virtual ADM_USUARIOS ADM_USUARIOS { get; set; }
    }
}
