//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_VERSION
    {
        public ART_MUS_FESTIVALES_VERSION()
        {
            this.ART_MUS_FESTIVALES_ENTIDADES_ALIADAS = new HashSet<ART_MUS_FESTIVALES_ENTIDADES_ALIADAS>();
            this.ART_MUS_FESTIVALES_EXPRESIONXVERSION = new HashSet<ART_MUS_FESTIVALES_EXPRESIONXVERSION>();
            this.ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION = new HashSet<ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION>();
            this.ART_MUS_LOCALIZACIONXVERSION = new HashSet<ART_MUS_LOCALIZACIONXVERSION>();
            this.ART_MUS_MATERIALMULTIMEDIA = new HashSet<ART_MUS_MATERIALMULTIMEDIA>();
            this.ART_MUS_TERRITORIOS_SONOROSXVERSION = new HashSet<ART_MUS_TERRITORIOS_SONOROSXVERSION>();
            this.ART_MUS_TIPOINGRESOXVERSION = new HashSet<ART_MUS_TIPOINGRESOXVERSION>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_FESTIVAL { get; set; }
        public Nullable<int> VERSION_FESTIVAL { get; set; }
        public string NOMBRE_VERSION { get; set; }
        public string DESCRIPCION_VERSION { get; set; }
        public string PRACTICAS_MUSICALES_CONGREGA { get; set; }
        public string FECHA_INICIO { get; set; }
        public string FECHA_FIN { get; set; }
        public Nullable<int> ID_TIPOLOGIA { get; set; }
        public string OTRA_TIPOLOGIA { get; set; }
        public string OTRA_MODALIDAD_PARTICIPACION { get; set; }
        public string OTRA_EXPRESION_ARTISTICA { get; set; }
        public Nullable<int> ID_FUENTE_FINANCIACION { get; set; }
        public Nullable<int> ID_FUENTE_FINANCIACION_SECUNDARIA { get; set; }
        public string OTRA_FUENTE_FINANCIACION_PRIMARIA { get; set; }
        public string OTRA_FUENTE_FINANCIACION_SECUNDARIA { get; set; }
        public Nullable<bool> USO_ESTAMPILLA_PROCULTURA { get; set; }
        public string DIRECTOR { get; set; }
        public Nullable<bool> PERTENECE_ORG_COLETIVA { get; set; }
        public string NOMBRE_ORGANIZACION { get; set; }
        public Nullable<int> ID_TIPO_ORGANIZADOR { get; set; }
        public string OTRO_TIPO_ORGANIZADOR { get; set; }
        public string CORREO_CONTACTO { get; set; }
        public string INSTAGRAM { get; set; }
        public string FACEBOOK { get; set; }
        public string PAGINA_WEB { get; set; }
        public string OTRO_ENLACE { get; set; }
        public string TELEFONO_CELULAR { get; set; }
        public string OBSERVACIONES_CONTACTO { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
    
        public virtual ART_MUS_FESTIVALES ART_MUS_FESTIVALES { get; set; }
        public virtual ART_MUS_FESTIVALES_ESTADO ART_MUS_FESTIVALES_ESTADO { get; set; }
        public virtual ICollection<ART_MUS_FESTIVALES_ENTIDADES_ALIADAS> ART_MUS_FESTIVALES_ENTIDADES_ALIADAS { get; set; }
        public virtual ICollection<ART_MUS_FESTIVALES_EXPRESIONXVERSION> ART_MUS_FESTIVALES_EXPRESIONXVERSION { get; set; }
        public virtual ART_MUS_FESTIVALES_FUENTE_FINANCIACION ART_MUS_FESTIVALES_FUENTE_FINANCIACION { get; set; }
        public virtual ART_MUS_FESTIVALES_FUENTE_FINANCIACION ART_MUS_FESTIVALES_FUENTE_FINANCIACION1 { get; set; }
        public virtual ICollection<ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION> ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION { get; set; }
        public virtual ART_MUS_FESTIVALES_TIPO_ORGANIZADOR ART_MUS_FESTIVALES_TIPO_ORGANIZADOR { get; set; }
        public virtual ART_MUS_FESTIVALES_TIPOLOGIA ART_MUS_FESTIVALES_TIPOLOGIA { get; set; }
        public virtual ICollection<ART_MUS_LOCALIZACIONXVERSION> ART_MUS_LOCALIZACIONXVERSION { get; set; }
        public virtual ICollection<ART_MUS_MATERIALMULTIMEDIA> ART_MUS_MATERIALMULTIMEDIA { get; set; }
        public virtual ICollection<ART_MUS_TERRITORIOS_SONOROSXVERSION> ART_MUS_TERRITORIOS_SONOROSXVERSION { get; set; }
        public virtual ICollection<ART_MUS_TIPOINGRESOXVERSION> ART_MUS_TIPOINGRESOXVERSION { get; set; }
    }
}
