//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_GRUPOS
    {
        public ART_MUSICA_GRUPOS()
        {
            this.ART_MUSICA_GRUPOEVENTOS = new HashSet<ART_MUSICA_GRUPOEVENTOS>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Enlace { get; set; }
        public string Contacto { get; set; }
        public string Telefono { get; set; }
        public int Orden { get; set; }
        public int CantidadMiembros { get; set; }
        public short EsGrupo { get; set; }
        public string Reseña { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual ICollection<ART_MUSICA_GRUPOEVENTOS> ART_MUSICA_GRUPOEVENTOS { get; set; }
    }
}
