//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ESCENARIO_DIAS
    {
        public int Id { get; set; }
        public int EscenarioId { get; set; }
        public int DiaId { get; set; }
    
        public virtual ART_MUSICA_ESCENARIOS ART_MUSICA_ESCENARIOS { get; set; }
    }
}
