//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ESCUELAS_DOCUMENTOS
    {
        public int Id { get; set; }
        public decimal EscuelaId { get; set; }
        public int DocumentoId { get; set; }
        public string Categoria { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ART_MUSICA_DOCUMENTOS ART_MUSICA_DOCUMENTOS { get; set; }
    }
}
