//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_RED_SOCIAL
    {
        public ART_MUSICA_RED_SOCIAL()
        {
            this.ART_MUSICA_RED_SOCIAL_ACTORES = new HashSet<ART_MUSICA_RED_SOCIAL_ACTORES>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Estilo { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public string Etiqueta { get; set; }
    
        public virtual ICollection<ART_MUSICA_RED_SOCIAL_ACTORES> ART_MUSICA_RED_SOCIAL_ACTORES { get; set; }
    }
}
