//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES
    {
        public ART_MUS_FESTIVALES()
        {
            this.ART_MUS_FESTIVALES_VERSION = new HashSet<ART_MUS_FESTIVALES_VERSION>();
        }
    
        public int id { get; set; }
        public Nullable<int> creado_por { get; set; }
        public string NOMBRE_FESTIVAL { get; set; }
        public Nullable<int> VERSIONES_REALIZADAS { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_VERSION { get; set; }
        public string DESCRIPCION_FESTIVAL { get; set; }
        public string CORREO_CONTACTO { get; set; }
        public string INSTAGRAM { get; set; }
        public string FACEBOOK { get; set; }
        public string PAGINA_WEB { get; set; }
        public string OTRO_ENLACE { get; set; }
        public string CELULAR { get; set; }
        public string OBSERVACIONES_CONTACTO { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
    
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUS_FESTIVALES_VERSION> ART_MUS_FESTIVALES_VERSION { get; set; }
        public virtual ART_MUS_FESTIVALES_ESTADO ART_MUS_FESTIVALES_ESTADO { get; set; }
    }
}
