//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_DOCUMENTOS
    {
        public ART_MUSICA_DOCUMENTOS()
        {
            this.ART_MUSICA_EVENTOS = new HashSet<ART_MUSICA_EVENTOS>();
            this.ART_MUSICA_ESCUELAS_DOCUMENTOS = new HashSet<ART_MUSICA_ESCUELAS_DOCUMENTOS>();
            this.ART_MUSICA_DOTACION_DOCUMENTOS = new HashSet<ART_MUSICA_DOTACION_DOCUMENTOS>();
            this.ART_MUSICA_HERRAMIENTAS = new HashSet<ART_MUSICA_HERRAMIENTAS>();
            this.ART_MUSICA_ACTIVIDADES = new HashSet<ART_MUSICA_ACTIVIDADES>();
            this.ART_MUSICA_CONVENIOS = new HashSet<ART_MUSICA_CONVENIOS>();
        }
    
        public int Id { get; set; }
        public string NombreArchivo { get; set; }
        public string Extension { get; set; }
        public byte[] Bytes { get; set; }
        public Nullable<decimal> TamanoArchivo { get; set; }
        public string TipoContenido { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS> ART_MUSICA_EVENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_ESCUELAS_DOCUMENTOS> ART_MUSICA_ESCUELAS_DOCUMENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_DOTACION_DOCUMENTOS> ART_MUSICA_DOTACION_DOCUMENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_HERRAMIENTAS> ART_MUSICA_HERRAMIENTAS { get; set; }
        public virtual ICollection<ART_MUSICA_ACTIVIDADES> ART_MUSICA_ACTIVIDADES { get; set; }
        public virtual ICollection<ART_MUSICA_CONVENIOS> ART_MUSICA_CONVENIOS { get; set; }
    }
}
