//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ESTADOS
    {
        public ART_MUSICA_ESTADOS()
        {
            this.ART_MUSICA_AGENTE = new HashSet<ART_MUSICA_AGENTE>();
            this.ART_MUSICA_ENTIDADES = new HashSet<ART_MUSICA_ENTIDADES>();
            this.ART_MUSICA_EVENTOS = new HashSet<ART_MUSICA_EVENTOS>();
            this.ART_MUSICA_AGRUPACION = new HashSet<ART_MUSICA_AGRUPACION>();
            this.ART_MUSICA_HERRAMIENTAS = new HashSet<ART_MUSICA_HERRAMIENTAS>();
            this.ART_MUSICA_EVENTOS_PERIODICOS = new HashSet<ART_MUSICA_EVENTOS_PERIODICOS>();
            this.ART_MUSICA_CONVOCATORIA_ESTIMULOS = new HashSet<ART_MUSICA_CONVOCATORIA_ESTIMULOS>();
            this.ART_MUSICA_SOLICITUD_USUARIOS = new HashSet<ART_MUSICA_SOLICITUD_USUARIOS>();
            this.ART_MUSICA_ENTIDAD_IDENTIFICACION = new HashSet<ART_MUSICA_ENTIDAD_IDENTIFICACION>();
            this.ART_MUSICA_ESCENARIOS = new HashSet<ART_MUSICA_ESCENARIOS>();
            this.ART_MUSICA_MOTIVO_HISTORICO = new HashSet<ART_MUSICA_MOTIVO_HISTORICO>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Mensaje { get; set; }
    
        public virtual ICollection<ART_MUSICA_AGENTE> ART_MUSICA_AGENTE { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDADES> ART_MUSICA_ENTIDADES { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS> ART_MUSICA_EVENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_AGRUPACION> ART_MUSICA_AGRUPACION { get; set; }
        public virtual ICollection<ART_MUSICA_HERRAMIENTAS> ART_MUSICA_HERRAMIENTAS { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS_PERIODICOS> ART_MUSICA_EVENTOS_PERIODICOS { get; set; }
        public virtual ICollection<ART_MUSICA_CONVOCATORIA_ESTIMULOS> ART_MUSICA_CONVOCATORIA_ESTIMULOS { get; set; }
        public virtual ICollection<ART_MUSICA_SOLICITUD_USUARIOS> ART_MUSICA_SOLICITUD_USUARIOS { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDAD_IDENTIFICACION> ART_MUSICA_ENTIDAD_IDENTIFICACION { get; set; }
        public virtual ICollection<ART_MUSICA_ESCENARIOS> ART_MUSICA_ESCENARIOS { get; set; }
        public virtual ICollection<ART_MUSICA_MOTIVO_HISTORICO> ART_MUSICA_MOTIVO_HISTORICO { get; set; }
    }
}
