//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA
    {
        public ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA()
        {
            this.ART_MUS_LOCALIZACIONXVERSION = new HashSet<ART_MUS_LOCALIZACIONXVERSION>();
        }
    
        public int ID { get; set; }
        public string DESCRPCION_ZONA_TITULACION_COLECTIVA { get; set; }
        public int ACTIVO { get; set; }
    
        public virtual ICollection<ART_MUS_LOCALIZACIONXVERSION> ART_MUS_LOCALIZACIONXVERSION { get; set; }
    }
}
