//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_PRACTICA_MUSICAL
    {
        public ART_MUSICA_PRACTICA_MUSICAL()
        {
            this.ART_MUSICA_ENTIDAD_FORMACION = new HashSet<ART_MUSICA_ENTIDAD_FORMACION>();
            this.ART_MUSICA_PRACTICAS_PNMC = new HashSet<ART_MUSICA_PRACTICAS_PNMC>();
            this.ART_MUSICA_FORMACION_PRACTICA = new HashSet<ART_MUSICA_FORMACION_PRACTICA>();
        }
    
        public short ART_MUS_PRAC_MUS_ID { get; set; }
        public string ART_MUS_PRAC_MUS_DESCRIPCION { get; set; }
    
        public virtual ICollection<ART_MUSICA_ENTIDAD_FORMACION> ART_MUSICA_ENTIDAD_FORMACION { get; set; }
        public virtual ICollection<ART_MUSICA_PRACTICAS_PNMC> ART_MUSICA_PRACTICAS_PNMC { get; set; }
        public virtual ICollection<ART_MUSICA_FORMACION_PRACTICA> ART_MUSICA_FORMACION_PRACTICA { get; set; }
    }
}
