//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_TRADICIONAL_GENEROS
    {
        public ART_MUSICA_TRADICIONAL_GENEROS()
        {
            this.ART_MUSICA_TRADICIONAL_AUDIOS = new HashSet<ART_MUSICA_TRADICIONAL_AUDIOS>();
            this.ART_MUSICA_TRADICIONAL_MUNICIPIOS = new HashSet<ART_MUSICA_TRADICIONAL_MUNICIPIOS>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> EjeId { get; set; }
    
        public virtual ICollection<ART_MUSICA_TRADICIONAL_AUDIOS> ART_MUSICA_TRADICIONAL_AUDIOS { get; set; }
        public virtual ICollection<ART_MUSICA_TRADICIONAL_MUNICIPIOS> ART_MUSICA_TRADICIONAL_MUNICIPIOS { get; set; }
        public virtual ART_MUSICA_EJES ART_MUSICA_EJES { get; set; }
    }
}
