//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_PRACTICA_GENERO
    {
        public int Id { get; set; }
        public int FormacionPracticaId { get; set; }
        public int GeneroId { get; set; }
        public string atributo { get; set; }
    
        public virtual ART_MUSICA_FORMACION_PRACTICA ART_MUSICA_FORMACION_PRACTICA { get; set; }
        public virtual ART_MUSICA_GENEROS_MUSICALES ART_MUSICA_GENEROS_MUSICALES { get; set; }
    }
}
