//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_CRONOGRAMA
    {
        public ART_MUSICA_CRONOGRAMA()
        {
            this.ART_MUSICA_ASISTENCIA = new HashSet<ART_MUSICA_ASISTENCIA>();
            this.ART_MUSICA_AVANCE = new HashSet<ART_MUSICA_AVANCE>();
            this.ART_MUSICA_CRONOGRAMAXAGENTE = new HashSet<ART_MUSICA_CRONOGRAMAXAGENTE>();
            this.ART_MUSICA_CONVENIO_DOTACION = new HashSet<ART_MUSICA_CONVENIO_DOTACION>();
            this.ART_MUSICA_EVALUACION = new HashSet<ART_MUSICA_EVALUACION>();
            this.ART_MUSICA_AUTOEVALUACION_RESPUESTA = new HashSet<ART_MUSICA_AUTOEVALUACION_RESPUESTA>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int ActividadId { get; set; }
        public string Cod_municipio { get; set; }
        public string Cod_departamento { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int Cupo { get; set; }
        public int UsuarioCreadorId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<decimal> EscuelaId { get; set; }
        public Nullable<int> Subtipo { get; set; }
    
        public virtual ICollection<ART_MUSICA_ASISTENCIA> ART_MUSICA_ASISTENCIA { get; set; }
        public virtual ICollection<ART_MUSICA_AVANCE> ART_MUSICA_AVANCE { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_CRONOGRAMAXAGENTE> ART_MUSICA_CRONOGRAMAXAGENTE { get; set; }
        public virtual ART_MUSICA_ACTIVIDADES ART_MUSICA_ACTIVIDADES { get; set; }
        public virtual ICollection<ART_MUSICA_CONVENIO_DOTACION> ART_MUSICA_CONVENIO_DOTACION { get; set; }
        public virtual ICollection<ART_MUSICA_EVALUACION> ART_MUSICA_EVALUACION { get; set; }
        public virtual ICollection<ART_MUSICA_AUTOEVALUACION_RESPUESTA> ART_MUSICA_AUTOEVALUACION_RESPUESTA { get; set; }
    }
}
