//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ENTIDAD_PRODUCCION
    {
        public decimal ENT_ID { get; set; }
        public short ENT_CANTIDAD_GIRAS_ULTIMO_ANIO { get; set; }
        public short ENT_CANTIDAD_PRESENTACIONES_LOCALIDAD_ULTIMO_ANIO { get; set; }
        public short ENT_CANTIDAD_DISCOS_ULTIMO_ANIO { get; set; }
        public short ENT_CANTIDAD_REPERTORIOS_ULTIMO_ANIO { get; set; }
        public short ENT_CANTIDAD_MATERIAL_DIVULGATIVO_ULTIMO_ANIO { get; set; }
        public short ENT_CANTIDAD_MATERIAL_APOYO_ULTIMO_ANIO { get; set; }
        public short ENT_CANTIDAD_AGRUPACIONES_CONFORMADAS_VIGENTES { get; set; }
        public Nullable<short> ENT_CANTIDAD_GIRAS_INTER_ULTIMO_ANIO { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
    }
}
