//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ESCUELA_REPERTORIOS
    {
        public int Id { get; set; }
        public decimal EscuelaId { get; set; }
        public string Nombre { get; set; }
        public string Compositor { get; set; }
        public string Arreglista { get; set; }
        public int Dificultad { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    }
}
