//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_CONVOCATORIAS
    {
        public ART_MUSICA_CONVOCATORIAS()
        {
            this.ART_MUSICA_CONVOCATORIA_ACTORES = new HashSet<ART_MUSICA_CONVOCATORIA_ACTORES>();
            this.ART_MUSICA_ENTIDAD_DOTACION = new HashSet<ART_MUSICA_ENTIDAD_DOTACION>();
            this.ART_MUSICA_PARTICIPACION = new HashSet<ART_MUSICA_PARTICIPACION>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Descripcion { get; set; }
        public int EstadoId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public Nullable<int> AgrupacionId { get; set; }
        public Nullable<decimal> EscuelaId { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public int TipoActorId { get; set; }
        public string NombreActor { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ART_MUSICA_AGRUPACION ART_MUSICA_AGRUPACION { get; set; }
        public virtual ICollection<ART_MUSICA_CONVOCATORIA_ACTORES> ART_MUSICA_CONVOCATORIA_ACTORES { get; set; }
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES { get; set; }
        public virtual ART_MUSICA_PARAMETROS_SERVICIOS ART_MUSICA_PARAMETROS_SERVICIOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDAD_DOTACION> ART_MUSICA_ENTIDAD_DOTACION { get; set; }
        public virtual ICollection<ART_MUSICA_PARTICIPACION> ART_MUSICA_PARTICIPACION { get; set; }
    }
}
