//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_RED_SOCIAL_ACTORES
    {
        public int Id { get; set; }
        public int RedSocialId { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public Nullable<int> AgrupacionId { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public string Valor { get; set; }
    
        public virtual ART_MUSICA_RED_SOCIAL ART_MUSICA_RED_SOCIAL { get; set; }
    }
}
