//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ESCUELA_OBSERVACION
    {
        public int Id { get; set; }
        public decimal EscuelaId { get; set; }
        public string Tipo { get; set; }
        public string Observaciones { get; set; }
        public string Recomendaciones { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
    }
}
