//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_DOTACION
    {
        public ART_MUSICA_DOTACION()
        {
            this.ART_MUSICA_DOTACION_DOCUMENTOS = new HashSet<ART_MUSICA_DOTACION_DOCUMENTOS>();
            this.ART_MUSICA_DOTACION_INSTRUMENTOS = new HashSet<ART_MUSICA_DOTACION_INSTRUMENTOS>();
        }
    
        public int Id { get; set; }
        public int EntidadId { get; set; }
        public decimal EscuelaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Identificacion { get; set; }
        public string Cargo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> ConvocatoriaId { get; set; }
    
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES { get; set; }
        public virtual ICollection<ART_MUSICA_DOTACION_DOCUMENTOS> ART_MUSICA_DOTACION_DOCUMENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_DOTACION_INSTRUMENTOS> ART_MUSICA_DOTACION_INSTRUMENTOS { get; set; }
    }
}
