//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_EVENTOS
    {
        public ART_MUSICA_EVENTOS()
        {
            this.ART_MUSICA_ARTISTAS_CELEBRA = new HashSet<ART_MUSICA_ARTISTAS_CELEBRA>();
            this.ART_MUSICA_GRUPOEVENTOS = new HashSet<ART_MUSICA_GRUPOEVENTOS>();
            this.ART_MUSICA_EVENTOS_RELACIONADOS = new HashSet<ART_MUSICA_EVENTOS_RELACIONADOS>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public decimal AreaArtisticaId { get; set; }
        public string EntidadOrganizadora { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public string CodDepartamento { get; set; }
        public string NombreDepartamento { get; set; }
        public string CodMunicipio { get; set; }
        public string NombreMunicipio { get; set; }
        public string LugarEvento { get; set; }
        public System.DateTime FechaEvento { get; set; }
        public string Descripción { get; set; }
        public byte[] Imagen { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Tipo { get; set; }
        public int AnoEvento { get; set; }
        public int UsuarioId { get; set; }
        public int EstadoId { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public Nullable<System.DateTime> FechaEventoFinal { get; set; }
        public Nullable<bool> EsNacional { get; set; }
        public Nullable<bool> Destacado { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ICollection<ART_MUSICA_ARTISTAS_CELEBRA> ART_MUSICA_ARTISTAS_CELEBRA { get; set; }
        public virtual ART_MUSICA_DOCUMENTOS ART_MUSICA_DOCUMENTOS { get; set; }
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_GRUPOEVENTOS> ART_MUSICA_GRUPOEVENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS_RELACIONADOS> ART_MUSICA_EVENTOS_RELACIONADOS { get; set; }
    }
}
