//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ROL
    {
        public ART_MUSICA_ROL()
        {
            this.ART_MUSICA_ROL_RECURSO = new HashSet<ART_MUSICA_ROL_RECURSO>();
            this.ART_MUSICA_USUARIO_ROL = new HashSet<ART_MUSICA_USUARIO_ROL>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual ICollection<ART_MUSICA_ROL_RECURSO> ART_MUSICA_ROL_RECURSO { get; set; }
        public virtual ICollection<ART_MUSICA_USUARIO_ROL> ART_MUSICA_USUARIO_ROL { get; set; }
    }
}
