//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_AUTOEVALUACION_RESPUESTA
    {
        public int Id { get; set; }
        public int PreguntaId { get; set; }
        public int ParticipanteId { get; set; }
        public int CronogramaId { get; set; }
        public bool respondio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ART_MUSICA_CRONOGRAMA ART_MUSICA_CRONOGRAMA { get; set; }
        public virtual ART_MUSICA_EVALUACION_PREGUNTAS ART_MUSICA_EVALUACION_PREGUNTAS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
    }
}
