//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ENTIDADES
    {
        public ART_MUSICA_ENTIDADES()
        {
            this.ART_MUSICA_ENTIDAD_TIPOENTIDAD = new HashSet<ART_MUSICA_ENTIDAD_TIPOENTIDAD>();
            this.ART_MUSICA_EVENTOS = new HashSet<ART_MUSICA_EVENTOS>();
            this.ART_MUSICA_CONVOCATORIAS = new HashSet<ART_MUSICA_CONVOCATORIAS>();
            this.ART_MUSICA_DOTACION = new HashSet<ART_MUSICA_DOTACION>();
            this.ART_MUSICA_ENTIDAD_DOTACION = new HashSet<ART_MUSICA_ENTIDAD_DOTACION>();
            this.ART_MUSICA_EVENTOS_PERIODICOS = new HashSet<ART_MUSICA_EVENTOS_PERIODICOS>();
            this.ART_MUSICA_ESCENARIOS = new HashSet<ART_MUSICA_ESCENARIOS>();
            this.ART_MUSICA_MOTIVO_HISTORICO = new HashSet<ART_MUSICA_MOTIVO_HISTORICO>();
            this.ART_MUSICA_CONVENIOS = new HashSet<ART_MUSICA_CONVENIOS>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Nit { get; set; }
        public Nullable<int> DigitoVerificacion { get; set; }
        public string CodigoMunicipio { get; set; }
        public string CodigoDepartamento { get; set; }
        public int CodigoPais { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public byte[] Imagen { get; set; }
        public string CorreoElectronico { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string LinkPortafolio { get; set; }
        public int ArtMusicaUsuarioId { get; set; }
        public int EstadoId { get; set; }
        public decimal ArdId { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Descripcion { get; set; }
        public string Naturaleza { get; set; }
        public Nullable<int> RedeSocialesId { get; set; }
    
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES1 { get; set; }
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES2 { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDAD_TIPOENTIDAD> ART_MUSICA_ENTIDAD_TIPOENTIDAD { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS> ART_MUSICA_EVENTOS { get; set; }
        public virtual ART_MUSICA_REDES_SOCIALES ART_MUSICA_REDES_SOCIALES { get; set; }
        public virtual ICollection<ART_MUSICA_CONVOCATORIAS> ART_MUSICA_CONVOCATORIAS { get; set; }
        public virtual ICollection<ART_MUSICA_DOTACION> ART_MUSICA_DOTACION { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDAD_DOTACION> ART_MUSICA_ENTIDAD_DOTACION { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS_PERIODICOS> ART_MUSICA_EVENTOS_PERIODICOS { get; set; }
        public virtual ICollection<ART_MUSICA_ESCENARIOS> ART_MUSICA_ESCENARIOS { get; set; }
        public virtual ICollection<ART_MUSICA_MOTIVO_HISTORICO> ART_MUSICA_MOTIVO_HISTORICO { get; set; }
        public virtual ICollection<ART_MUSICA_CONVENIOS> ART_MUSICA_CONVENIOS { get; set; }
    }
}
