//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_CATEGORIA_ESCUELA
    {
        public ART_MUSICA_CATEGORIA_ESCUELA()
        {
            this.ART_MUSICA_ENTIDAD_CATEGORIZACION = new HashSet<ART_MUSICA_ENTIDAD_CATEGORIZACION>();
        }
    
        public short ID_CATEGORIA { get; set; }
        public string DESCRIPCION_CATEGORIA { get; set; }
    
        public virtual ICollection<ART_MUSICA_ENTIDAD_CATEGORIZACION> ART_MUSICA_ENTIDAD_CATEGORIZACION { get; set; }
    }
}
