//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_FORMULARIOS_REGISTRO
    {
        public ART_ME_FORMULARIOS_REGISTRO()
        {
            this.ART_ME_FORMULARIOS_VALORES = new HashSet<ART_ME_FORMULARIOS_VALORES>();
            this.ART_MUSICA_FORMULARIO_ARCHIVOS = new HashSet<ART_MUSICA_FORMULARIO_ARCHIVOS>();
        }
    
        public decimal FRE_ID { get; set; }
        public decimal ENT_ID { get; set; }
        public System.DateTime FRE_FECHA_REGISTRO { get; set; }
    
        public virtual ICollection<ART_ME_FORMULARIOS_VALORES> ART_ME_FORMULARIOS_VALORES { get; set; }
        public virtual ICollection<ART_MUSICA_FORMULARIO_ARCHIVOS> ART_MUSICA_FORMULARIO_ARCHIVOS { get; set; }
    }
}
