//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ROL_RECURSO
    {
        public int Id { get; set; }
        public Nullable<int> RolId { get; set; }
        public Nullable<int> RecId { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int NumMenu { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual ART_MUSICA_RECURSO ART_MUSICA_RECURSO { get; set; }
        public virtual ART_MUSICA_ROL ART_MUSICA_ROL { get; set; }
    }
}
