//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ASISTENCIA
    {
        public int Id { get; set; }
        public int ParticipanteId { get; set; }
        public int CronogramaId { get; set; }
        public System.DateTime FechaAsistencia { get; set; }
        public Nullable<int> UsuarioCreadorId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<bool> Asistio { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ART_MUSICA_CRONOGRAMA ART_MUSICA_CRONOGRAMA { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
    }
}
