//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_TIPO_DOCUMENTO_CREACION
    {
        public ART_MUSICA_TIPO_DOCUMENTO_CREACION()
        {
            this.ART_MUS_TIP_DOC_CRE_ENT_INSTITUC = new HashSet<ART_MUS_TIP_DOC_CRE_ENT_INSTITUC>();
        }
    
        public short ART_MUS_TIP_DOC_CRE_ID { get; set; }
        public string ART_MUS_TIP_DOC_CRE_DESCRPICION { get; set; }
    
        public virtual ICollection<ART_MUS_TIP_DOC_CRE_ENT_INSTITUC> ART_MUS_TIP_DOC_CRE_ENT_INSTITUC { get; set; }
    }
}
