//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_INFRAESTRUCTURA_AREAS_ARTISTICAS
    {
        public decimal ARD_ID { get; set; }
        public decimal INF_ID { get; set; }
    
        public virtual ART_INFRAESTRUCTURA_ENTIDADES ART_INFRAESTRUCTURA_ENTIDADES { get; set; }
    }
}
