//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_MOTIVO_HISTORICO
    {
        public int Id { get; set; }
        public Nullable<int> AgrupacionId { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public Nullable<decimal> EscuelaId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int EstadoId { get; set; }
        public string NombreEstado { get; set; }
        public string Motivo { get; set; }
        public string Tipo { get; set; }
        public string Modulo { get; set; }
        public string NombreUsuario { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ART_MUSICA_AGRUPACION ART_MUSICA_AGRUPACION { get; set; }
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
    }
}
