//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_EVENTOS_PERIODICOS
    {
        public ART_MUSICA_EVENTOS_PERIODICOS()
        {
            this.ART_MUSICA_EVENTOS_RELACIONADOS = new HashSet<ART_MUSICA_EVENTOS_RELACIONADOS>();
            this.ART_MUSICA_RED_SOCIAL_ESCENARIOS = new HashSet<ART_MUSICA_RED_SOCIAL_ESCENARIOS>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Version { get; set; }
        public string Descripcion { get; set; }
        public string CodDepto { get; set; }
        public string Departamento { get; set; }
        public string CodMunicipio { get; set; }
        public string Municipio { get; set; }
        public string Lugar { get; set; }
        public int ClasificacionId { get; set; }
        public int EntidadId { get; set; }
        public string NombreEntidad { get; set; }
        public string PaginaWeb { get; set; }
        public string UrlVideoYoutube { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public int EstadoId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public bool EsActivo { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual ART_MUSICA_ENTIDADES ART_MUSICA_ENTIDADES { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS_RELACIONADOS> ART_MUSICA_EVENTOS_RELACIONADOS { get; set; }
        public virtual ICollection<ART_MUSICA_RED_SOCIAL_ESCENARIOS> ART_MUSICA_RED_SOCIAL_ESCENARIOS { get; set; }
    }
}
