//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_FORMULARIOS_LISTAS
    {
        public ART_ME_FORMULARIOS_LISTAS()
        {
            this.ART_ME_FORMULARIOS_COLUMNAS = new HashSet<ART_ME_FORMULARIOS_COLUMNAS>();
            this.ART_ME_FORMULARIOS_LISTAS_ELEMENTOS = new HashSet<ART_ME_FORMULARIOS_LISTAS_ELEMENTOS>();
        }
    
        public decimal FLI_ID { get; set; }
        public string FLI_NOMBRE { get; set; }
        public string FLI_DESCRIPCION { get; set; }
    
        public virtual ICollection<ART_ME_FORMULARIOS_COLUMNAS> ART_ME_FORMULARIOS_COLUMNAS { get; set; }
        public virtual ICollection<ART_ME_FORMULARIOS_LISTAS_ELEMENTOS> ART_ME_FORMULARIOS_LISTAS_ELEMENTOS { get; set; }
    }
}
