//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_PARTICIPACION
    {
        public int Id { get; set; }
        public int ConvocatoriaId { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public Nullable<int> AgrupacionId { get; set; }
        public Nullable<decimal> EscuelaId { get; set; }
        public int EstadoId { get; set; }
        public int UsuarioId { get; set; }
        public string RelacionadoA { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Nombre { get; set; }
    
        public virtual ART_MUSICA_CONVOCATORIAS ART_MUSICA_CONVOCATORIAS { get; set; }
        public virtual ART_MUSICA_PARAMETROS_SERVICIOS ART_MUSICA_PARAMETROS_SERVICIOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
    }
}
