//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_CONVOCATORIA_ESTIMULOS
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int EstadoId { get; set; }
        public int UsuarioId { get; set; }
        public int Periodo { get; set; }
    
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
    }
}
