//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_TIPO_DATO_RETORNO
    {
        public ART_MUSICA_TIPO_DATO_RETORNO()
        {
            this.ART_MUSICA_FACTOR_CATEGORIZACION = new HashSet<ART_MUSICA_FACTOR_CATEGORIZACION>();
        }
    
        public short ID_TIPO_DATO_RETORNO { get; set; }
        public string DESCRIPCION_TIPO_DATO_RETORNO { get; set; }
    
        public virtual ICollection<ART_MUSICA_FACTOR_CATEGORIZACION> ART_MUSICA_FACTOR_CATEGORIZACION { get; set; }
    }
}
