//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ESCUELA_ASESORIA
    {
        public int Id { get; set; }
        public decimal EscuelaId { get; set; }
        public string PracticaColectiva { get; set; }
        public string NombreAgrupacion { get; set; }
        public Nullable<int> PromedioAnualPresentaciones { get; set; }
        public Nullable<int> PromedioMesesPresentaciones { get; set; }
        public string AspectoAsesorado { get; set; }
        public string Recomendacion { get; set; }
        public string Concepto { get; set; }
        public string Mecanismo { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public string NombreDirector { get; set; }
        public string Basico { get; set; }
        public string Medio { get; set; }
        public string Avanzado { get; set; }
        public Nullable<int> Conformacion { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
    }
}
