//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_TIPOINGRESO
    {
        public ART_MUS_TIPOINGRESO()
        {
            this.ART_MUS_TIPOINGRESOXVERSION = new HashSet<ART_MUS_TIPOINGRESOXVERSION>();
        }
    
        public int ID { get; set; }
        public string TIPO_INGRESO { get; set; }
    
        public virtual ICollection<ART_MUS_TIPOINGRESOXVERSION> ART_MUS_TIPOINGRESOXVERSION { get; set; }
    }
}
