//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ENTIDAD_INFRAESTRUCTURA
    {
        public ART_MUSICA_ENTIDAD_INFRAESTRUCTURA()
        {
            this.ART_MUSICA_FUENTES_DOTACION = new HashSet<ART_MUSICA_FUENTES_DOTACION>();
            this.ART_MUSICA_MATERIAL_PEDAGOGICO = new HashSet<ART_MUSICA_MATERIAL_PEDAGOGICO>();
            this.ART_MUSICA_NIVEL_FUENTES_DOTACION = new HashSet<ART_MUSICA_NIVEL_FUENTES_DOTACION>();
        }
    
        public decimal ENT_ID { get; set; }
        public bool ENT_SEDE_ASIGNADA_SOPORTE_ESCRITO { get; set; }
        public bool ENT_SEDE_EQUIP_MOBIL_INSTRUM { get; set; }
        public bool ENT_SEDE_ADEC_ACUSTIC { get; set; }
        public short ENT_CANTIDAD_INSTR_CUERDAS_PULSADAS { get; set; }
        public short ENT_CANTIDAD_INSTR_CUERDAS_SINFONICAS { get; set; }
        public short ENT_CANTIDAD_INSTR_VIENTOS_MADERAS { get; set; }
        public short ENT_CANTIDAD_INSTR_VIENTOS_METALES { get; set; }
        public short ENT_CANTIDAD_INSTR_PERCUSION_MENOR { get; set; }
        public short ENT_CANTIDAD_INSTR_PERCUSION_SINFONICA { get; set; }
        public short ENT_CANTIDAD_INSTR_OTROS { get; set; }
        public short ENT_CANTIDAD_INSTR_TOTAL { get; set; }
        public bool ENT_MATERIAL_PEDAGOGICO { get; set; }
        public short ENT_CANTIDAD_TITULOS_BIBLIOGRAFICOS { get; set; }
        public string ENT_SEDE_LUGAR { get; set; }
        public Nullable<short> ENT_CANTIDAD_SILLAS { get; set; }
        public Nullable<short> ENT_CANTIDAD_ATRILES { get; set; }
        public Nullable<short> ENT_CANTIDAD_TABLEROS { get; set; }
        public Nullable<short> ENT_CANTIDAD_ESTANTERIA { get; set; }
        public Nullable<short> ENT_SEDE_PORCENTAJE_ADEC_ACUSTIC { get; set; }
        public string ENT_SEDE_OTRA_SOLUCION_ADEC_ACUSTIC { get; set; }
        public Nullable<bool> ENT_TIENE_INTERNET { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ICollection<ART_MUSICA_FUENTES_DOTACION> ART_MUSICA_FUENTES_DOTACION { get; set; }
        public virtual ICollection<ART_MUSICA_MATERIAL_PEDAGOGICO> ART_MUSICA_MATERIAL_PEDAGOGICO { get; set; }
        public virtual ICollection<ART_MUSICA_NIVEL_FUENTES_DOTACION> ART_MUSICA_NIVEL_FUENTES_DOTACION { get; set; }
    }
}
