//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ACTIVIDADES
    {
        public ART_MUSICA_ACTIVIDADES()
        {
            this.ART_MUSICA_CONTENIDOS = new HashSet<ART_MUSICA_CONTENIDOS>();
            this.ART_MUSICA_CRONOGRAMA = new HashSet<ART_MUSICA_CRONOGRAMA>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int TipoActividadId { get; set; }
        public int ConvenioId { get; set; }
        public decimal ValorProgramado { get; set; }
        public decimal ValorEjecutado { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> Minimo_Dias { get; set; }
        public Nullable<int> DocumentoId { get; set; }
    
        public virtual ART_MUSICA_CONVENIOS ART_MUSICA_CONVENIOS { get; set; }
        public virtual ICollection<ART_MUSICA_CONTENIDOS> ART_MUSICA_CONTENIDOS { get; set; }
        public virtual ICollection<ART_MUSICA_CRONOGRAMA> ART_MUSICA_CRONOGRAMA { get; set; }
        public virtual ART_MUSICA_DOCUMENTOS ART_MUSICA_DOCUMENTOS { get; set; }
    }
}
