//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_RECURSO
    {
        public ART_MUSICA_RECURSO()
        {
            this.ART_MUSICA_ROL_RECURSO = new HashSet<ART_MUSICA_ROL_RECURSO>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Descripcion { get; set; }
        public string Ruta { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public string Titulo { get; set; }
        public string estilo { get; set; }
    
        public virtual ICollection<ART_MUSICA_ROL_RECURSO> ART_MUSICA_ROL_RECURSO { get; set; }
    }
}
