//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_EVALUACION_PREGUNTAS
    {
        public ART_MUSICA_EVALUACION_PREGUNTAS()
        {
            this.ART_MUSICA_AUTOEVALUACION_RESPUESTA = new HashSet<ART_MUSICA_AUTOEVALUACION_RESPUESTA>();
        }
    
        public int Id { get; set; }
        public string Pregunta { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public int UsuarioCreadorId { get; set; }
    
        public virtual ICollection<ART_MUSICA_AUTOEVALUACION_RESPUESTA> ART_MUSICA_AUTOEVALUACION_RESPUESTA { get; set; }
    }
}
