//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_AGENTE
    {
        public ART_MUSICA_AGENTE()
        {
            this.ART_MUSICA_AGENTE_EXPERIENCIA = new HashSet<ART_MUSICA_AGENTE_EXPERIENCIA>();
            this.ART_MUSICA_AGENTE_AGRUPACION = new HashSet<ART_MUSICA_AGENTE_AGRUPACION>();
            this.ART_MUSICA_EVENTOS = new HashSet<ART_MUSICA_EVENTOS>();
            this.ART_MUSICA_AGENTEXOCUPACION = new HashSet<ART_MUSICA_AGENTEXOCUPACION>();
            this.ART_MUSICA_AGENTE_SERVICIO = new HashSet<ART_MUSICA_AGENTE_SERVICIO>();
            this.ART_MUSICA_AGENTES_INSTRUMENTOS = new HashSet<ART_MUSICA_AGENTES_INSTRUMENTOS>();
            this.ART_MUSICA_AGENTE_INTERESES = new HashSet<ART_MUSICA_AGENTE_INTERESES>();
            this.ART_MUSICA_CONVOCATORIAS = new HashSet<ART_MUSICA_CONVOCATORIAS>();
            this.ART_MUSICA_AGENTE_OFICIOS = new HashSet<ART_MUSICA_AGENTE_OFICIOS>();
            this.ART_MUSICA_ESCENARIOS = new HashSet<ART_MUSICA_ESCENARIOS>();
            this.ART_MUSICA_MOTIVO_HISTORICO = new HashSet<ART_MUSICA_MOTIVO_HISTORICO>();
            this.ART_MUSICA_AGENTEXCONVENIO = new HashSet<ART_MUSICA_AGENTEXCONVENIO>();
            this.ART_MUSICA_CONVENIOS = new HashSet<ART_MUSICA_CONVENIOS>();
            this.ART_MUSICA_ASISTENCIA = new HashSet<ART_MUSICA_ASISTENCIA>();
            this.ART_MUSICA_AVANCE = new HashSet<ART_MUSICA_AVANCE>();
            this.ART_MUSICA_AVANCE1 = new HashSet<ART_MUSICA_AVANCE>();
            this.ART_MUSICA_CRONOGRAMAXAGENTE = new HashSet<ART_MUSICA_CRONOGRAMAXAGENTE>();
            this.ART_MUSICA_EVALUACION = new HashSet<ART_MUSICA_EVALUACION>();
            this.ART_MUSICA_AUTOEVALUACION_RESPUESTA = new HashSet<ART_MUSICA_AUTOEVALUACION_RESPUESTA>();
        }
    
        public int ID { get; set; }
        public int IdADM_ART_USUARIO { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SedundoApellido { get; set; }
        public byte[] Imagen { get; set; }
        public int CodTipoDocumento { get; set; }
        public string Identificacion { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string CodPais { get; set; }
        public string CodMunicipio { get; set; }
        public string OtraCiudad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string LinkPortafolio { get; set; }
        public Nullable<decimal> ARD_ID { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public int EstadoId { get; set; }
        public string CorreoElectronico { get; set; }
        public string CodigoDepartamento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ARE_ID { get; set; }
        public string NombreArtistico { get; set; }
        public Nullable<int> RedeSocialesId { get; set; }
    
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTE_EXPERIENCIA> ART_MUSICA_AGENTE_EXPERIENCIA { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTE_AGRUPACION> ART_MUSICA_AGENTE_AGRUPACION { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS> ART_MUSICA_EVENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTEXOCUPACION> ART_MUSICA_AGENTEXOCUPACION { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTE_SERVICIO> ART_MUSICA_AGENTE_SERVICIO { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTES_INSTRUMENTOS> ART_MUSICA_AGENTES_INSTRUMENTOS { get; set; }
        public virtual ART_MUSICA_REDES_SOCIALES ART_MUSICA_REDES_SOCIALES { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTE_INTERESES> ART_MUSICA_AGENTE_INTERESES { get; set; }
        public virtual ICollection<ART_MUSICA_CONVOCATORIAS> ART_MUSICA_CONVOCATORIAS { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTE_OFICIOS> ART_MUSICA_AGENTE_OFICIOS { get; set; }
        public virtual ICollection<ART_MUSICA_ESCENARIOS> ART_MUSICA_ESCENARIOS { get; set; }
        public virtual ICollection<ART_MUSICA_MOTIVO_HISTORICO> ART_MUSICA_MOTIVO_HISTORICO { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTEXCONVENIO> ART_MUSICA_AGENTEXCONVENIO { get; set; }
        public virtual ICollection<ART_MUSICA_CONVENIOS> ART_MUSICA_CONVENIOS { get; set; }
        public virtual ICollection<ART_MUSICA_ASISTENCIA> ART_MUSICA_ASISTENCIA { get; set; }
        public virtual ICollection<ART_MUSICA_AVANCE> ART_MUSICA_AVANCE { get; set; }
        public virtual ICollection<ART_MUSICA_AVANCE> ART_MUSICA_AVANCE1 { get; set; }
        public virtual ICollection<ART_MUSICA_CRONOGRAMAXAGENTE> ART_MUSICA_CRONOGRAMAXAGENTE { get; set; }
        public virtual ICollection<ART_MUSICA_EVALUACION> ART_MUSICA_EVALUACION { get; set; }
        public virtual ICollection<ART_MUSICA_AUTOEVALUACION_RESPUESTA> ART_MUSICA_AUTOEVALUACION_RESPUESTA { get; set; }
    }
}
