//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_GRUPOEVENTOS
    {
        public int Id { get; set; }
        public int EventoId { get; set; }
        public int GrupoId { get; set; }
    
        public virtual ART_MUSICA_EVENTOS ART_MUSICA_EVENTOS { get; set; }
        public virtual ART_MUSICA_GRUPOS ART_MUSICA_GRUPOS { get; set; }
    }
}
