//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_INFRAESTRUCTURA_ENTIDADES
    {
        public ART_INFRAESTRUCTURA_ENTIDADES()
        {
            this.ART_INFRAESTRUCTURA_AREAS_ARTISTICAS = new HashSet<ART_INFRAESTRUCTURA_AREAS_ARTISTICAS>();
        }
    
        public decimal INF_ID { get; set; }
        public decimal END_ID { get; set; }
        public string INF_NOMBRE { get; set; }
        public string INF_DIRECTOR { get; set; }
        public string INF_ANO_INICIO_ACTIVIDADES { get; set; }
        public int ZOP_ID { get; set; }
        public string ZON_ID { get; set; }
        public string INF_AREA { get; set; }
        public string INF_DIRECCION { get; set; }
        public string INF_TIENE_TELEFONO { get; set; }
        public string INF_NUMERO_TELEFONO { get; set; }
        public string INF_TIENE_FAX { get; set; }
        public string INF_NUMERO_FAX { get; set; }
        public string INF_APARTADO_AEREO { get; set; }
        public string INF_TIENE_CORREO { get; set; }
        public string INF_CORREO_ELECTRONICO { get; set; }
        public string INF_CONFIRMACION_CORREO { get; set; }
        public string INF_PAGINA_WEB { get; set; }
        public decimal CAM_ID { get; set; }
        public decimal ARD_ID { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ICollection<ART_INFRAESTRUCTURA_AREAS_ARTISTICAS> ART_INFRAESTRUCTURA_AREAS_ARTISTICAS { get; set; }
        public virtual BAS_ZONAS_GEOGRAFICAS BAS_ZONAS_GEOGRAFICAS { get; set; }
        public virtual BAS_ZONAS_PAISES BAS_ZONAS_PAISES { get; set; }
    }
}
