//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_USUARIO
    {
        public ART_MUSICA_USUARIO()
        {
            this.ART_MUSICA_AGENTE = new HashSet<ART_MUSICA_AGENTE>();
            this.ART_MUSICA_USUARIO_ROL = new HashSet<ART_MUSICA_USUARIO_ROL>();
            this.ART_MUSICA_ENTIDADES = new HashSet<ART_MUSICA_ENTIDADES>();
            this.ART_MUSICA_DOCUMENTOS = new HashSet<ART_MUSICA_DOCUMENTOS>();
            this.ART_MUSICA_ARTISTAS_CELEBRA = new HashSet<ART_MUSICA_ARTISTAS_CELEBRA>();
            this.ART_MUSICA_EVENTOS = new HashSet<ART_MUSICA_EVENTOS>();
            this.ART_MUSICA_REGISTRO_OPERACION = new HashSet<ART_MUSICA_REGISTRO_OPERACION>();
            this.ART_MUSICA_AGRUPACION = new HashSet<ART_MUSICA_AGRUPACION>();
            this.ART_MUSICA_CONVOCATORIAS = new HashSet<ART_MUSICA_CONVOCATORIAS>();
            this.ART_MUSICA_PARTICIPACION = new HashSet<ART_MUSICA_PARTICIPACION>();
            this.ART_MUSICA_MODULO_SERVICIOS = new HashSet<ART_MUSICA_MODULO_SERVICIOS>();
            this.ART_MUSICA_MODULO_SERVICIOS1 = new HashSet<ART_MUSICA_MODULO_SERVICIOS>();
            this.ART_MUSICA_HERRAMIENTAS = new HashSet<ART_MUSICA_HERRAMIENTAS>();
            this.ART_MUSICA_EVENTOS_PERIODICOS = new HashSet<ART_MUSICA_EVENTOS_PERIODICOS>();
            this.ART_MUSICA_CONVOCATORIA_ESTIMULOS = new HashSet<ART_MUSICA_CONVOCATORIA_ESTIMULOS>();
            this.ART_MUSICA_SOLICITUD_USUARIOS = new HashSet<ART_MUSICA_SOLICITUD_USUARIOS>();
            this.ART_MUSICA_ESCENARIOS = new HashSet<ART_MUSICA_ESCENARIOS>();
            this.ART_MUSICA_MOTIVO_HISTORICO = new HashSet<ART_MUSICA_MOTIVO_HISTORICO>();
            this.ART_MUSICA_AGENTEXCONVENIO = new HashSet<ART_MUSICA_AGENTEXCONVENIO>();
            this.ART_MUSICA_CONTENIDOS = new HashSet<ART_MUSICA_CONTENIDOS>();
            this.ART_MUSICA_CONVENIOS = new HashSet<ART_MUSICA_CONVENIOS>();
            this.ART_MUSICA_ASISTENCIA = new HashSet<ART_MUSICA_ASISTENCIA>();
            this.ART_MUSICA_AVANCE = new HashSet<ART_MUSICA_AVANCE>();
            this.ART_MUSICA_CRONOGRAMA = new HashSet<ART_MUSICA_CRONOGRAMA>();
            this.ART_MUSICA_CRONOGRAMAXAGENTE = new HashSet<ART_MUSICA_CRONOGRAMAXAGENTE>();
            this.ART_MUSICA_EVALUACION = new HashSet<ART_MUSICA_EVALUACION>();
            this.ART_MUSICA_AUTOEVALUACION_RESPUESTA = new HashSet<ART_MUSICA_AUTOEVALUACION_RESPUESTA>();
            this.ART_MUS_FESTIVALES = new HashSet<ART_MUS_FESTIVALES>();
        }
    
        public int Id { get; set; }
        public string IdUserRSS { get; set; }
        public string TipoRSS { get; set; }
        public string Email { get; set; }
        public string Identificacion { get; set; }
        public string CodTipoDocumento { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string CodPais { get; set; }
        public string CodDpto { get; set; }
        public string CodMunicipio { get; set; }
        public string Sexo { get; set; }
        public Nullable<bool> esUsuarioInterno { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Imagen { get; set; }
        public string Contraseña { get; set; }
        public byte[] ImagenUsuario { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string SegundoApellido { get; set; }
    
        public virtual ICollection<ART_MUSICA_AGENTE> ART_MUSICA_AGENTE { get; set; }
        public virtual ICollection<ART_MUSICA_USUARIO_ROL> ART_MUSICA_USUARIO_ROL { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDADES> ART_MUSICA_ENTIDADES { get; set; }
        public virtual ICollection<ART_MUSICA_DOCUMENTOS> ART_MUSICA_DOCUMENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_ARTISTAS_CELEBRA> ART_MUSICA_ARTISTAS_CELEBRA { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS> ART_MUSICA_EVENTOS { get; set; }
        public virtual ICollection<ART_MUSICA_REGISTRO_OPERACION> ART_MUSICA_REGISTRO_OPERACION { get; set; }
        public virtual ICollection<ART_MUSICA_AGRUPACION> ART_MUSICA_AGRUPACION { get; set; }
        public virtual ICollection<ART_MUSICA_CONVOCATORIAS> ART_MUSICA_CONVOCATORIAS { get; set; }
        public virtual ICollection<ART_MUSICA_PARTICIPACION> ART_MUSICA_PARTICIPACION { get; set; }
        public virtual ICollection<ART_MUSICA_MODULO_SERVICIOS> ART_MUSICA_MODULO_SERVICIOS { get; set; }
        public virtual ICollection<ART_MUSICA_MODULO_SERVICIOS> ART_MUSICA_MODULO_SERVICIOS1 { get; set; }
        public virtual ICollection<ART_MUSICA_HERRAMIENTAS> ART_MUSICA_HERRAMIENTAS { get; set; }
        public virtual ICollection<ART_MUSICA_EVENTOS_PERIODICOS> ART_MUSICA_EVENTOS_PERIODICOS { get; set; }
        public virtual ICollection<ART_MUSICA_CONVOCATORIA_ESTIMULOS> ART_MUSICA_CONVOCATORIA_ESTIMULOS { get; set; }
        public virtual ICollection<ART_MUSICA_SOLICITUD_USUARIOS> ART_MUSICA_SOLICITUD_USUARIOS { get; set; }
        public virtual ICollection<ART_MUSICA_ESCENARIOS> ART_MUSICA_ESCENARIOS { get; set; }
        public virtual ICollection<ART_MUSICA_MOTIVO_HISTORICO> ART_MUSICA_MOTIVO_HISTORICO { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTEXCONVENIO> ART_MUSICA_AGENTEXCONVENIO { get; set; }
        public virtual ICollection<ART_MUSICA_CONTENIDOS> ART_MUSICA_CONTENIDOS { get; set; }
        public virtual ICollection<ART_MUSICA_CONVENIOS> ART_MUSICA_CONVENIOS { get; set; }
        public virtual ICollection<ART_MUSICA_ASISTENCIA> ART_MUSICA_ASISTENCIA { get; set; }
        public virtual ICollection<ART_MUSICA_AVANCE> ART_MUSICA_AVANCE { get; set; }
        public virtual ICollection<ART_MUSICA_CRONOGRAMA> ART_MUSICA_CRONOGRAMA { get; set; }
        public virtual ICollection<ART_MUSICA_CRONOGRAMAXAGENTE> ART_MUSICA_CRONOGRAMAXAGENTE { get; set; }
        public virtual ICollection<ART_MUSICA_EVALUACION> ART_MUSICA_EVALUACION { get; set; }
        public virtual ICollection<ART_MUSICA_AUTOEVALUACION_RESPUESTA> ART_MUSICA_AUTOEVALUACION_RESPUESTA { get; set; }
        public virtual ICollection<ART_MUS_FESTIVALES> ART_MUS_FESTIVALES { get; set; }
    }
}
