//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_REDES_SOCIALES
    {
        public ART_MUSICA_REDES_SOCIALES()
        {
            this.ART_MUSICA_AGENTE = new HashSet<ART_MUSICA_AGENTE>();
            this.ART_MUSICA_ENTIDADES = new HashSet<ART_MUSICA_ENTIDADES>();
        }
    
        public int Id { get; set; }
        public string PefilFacebook { get; set; }
        public string PerfilTwitter { get; set; }
        public string PaginaWeb { get; set; }
        public string CanalYoutube { get; set; }
        public string PerfilSoundCloud { get; set; }
        public string PerfilFlickr { get; set; }
    
        public virtual ICollection<ART_MUSICA_AGENTE> ART_MUSICA_AGENTE { get; set; }
        public virtual ICollection<ART_MUSICA_ENTIDADES> ART_MUSICA_ENTIDADES { get; set; }
    }
}
