//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_EJES
    {
        public ART_MUSICA_EJES()
        {
            this.ART_MUSICA_TRADICIONAL_GENEROS = new HashSet<ART_MUSICA_TRADICIONAL_GENEROS>();
            this.ART_MUSICA_TRADICIONAL_MUNICIPIOS = new HashSet<ART_MUSICA_TRADICIONAL_MUNICIPIOS>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Resena { get; set; }
        public string Ruta { get; set; }
        public string RutaFoto { get; set; }
        public string Estilo { get; set; }
    
        public virtual ICollection<ART_MUSICA_TRADICIONAL_GENEROS> ART_MUSICA_TRADICIONAL_GENEROS { get; set; }
        public virtual ICollection<ART_MUSICA_TRADICIONAL_MUNICIPIOS> ART_MUSICA_TRADICIONAL_MUNICIPIOS { get; set; }
    }
}
