//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_AGRUPACION_GENEROS
    {
        public int Id { get; set; }
        public int AgrupacionId { get; set; }
        public Nullable<int> GeneroId { get; set; }
        public string Atributo { get; set; }
    
        public virtual ART_MUSICA_AGRUPACION ART_MUSICA_AGRUPACION { get; set; }
    }
}
