//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_AGENTES_INSTRUMENTOS
    {
        public int Id { get; set; }
        public int AgenteId { get; set; }
        public int OficioId { get; set; }
        public int InstrumentoId { get; set; }
        public string Instrumento { get; set; }
        public bool Estado { get; set; }
    
        public virtual ART_MUSICA_AGENTE ART_MUSICA_AGENTE { get; set; }
        public virtual ART_MUSICA_OFICIOS ART_MUSICA_OFICIOS { get; set; }
    }
}
