//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_PRACTICA_NIVEL
    {
        public int Id { get; set; }
        public decimal EscuelaId { get; set; }
        public int FormacionPracticaId { get; set; }
        public string Nivel { get; set; }
        public int CantidadGrupos { get; set; }
        public int CantidadIntegrantes { get; set; }
        public int HorasSemanal { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ART_MUSICA_FORMACION_PRACTICA ART_MUSICA_FORMACION_PRACTICA { get; set; }
    }
}
