//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_INTERESES
    {
        public ART_MUSICA_INTERESES()
        {
            this.ART_MUSICA_AGENTE_INTERESES = new HashSet<ART_MUSICA_AGENTE_INTERESES>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> ProcesoId { get; set; }
        public bool Estado { get; set; }
    
        public virtual ART_MUSICA_PROCESOS ART_MUSICA_PROCESOS { get; set; }
        public virtual ICollection<ART_MUSICA_AGENTE_INTERESES> ART_MUSICA_AGENTE_INTERESES { get; set; }
    }
}
