//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS
    {
        public ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS()
        {
            this.ART_MUS_FESTIVALES_EXPRESIONXVERSION = new HashSet<ART_MUS_FESTIVALES_EXPRESIONXVERSION>();
        }
    
        public int ID { get; set; }
        public string EXPRESION_ARTISTICA { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual ICollection<ART_MUS_FESTIVALES_EXPRESIONXVERSION> ART_MUS_FESTIVALES_EXPRESIONXVERSION { get; set; }
    }
}
