//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_EXPRESIONXVERSION
    {
        public int ID { get; set; }
        public int ID_VERSION { get; set; }
        public int ID_EXPRESION_ARTISTICA { get; set; }
    
        public virtual ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS { get; set; }
        public virtual ART_MUS_FESTIVALES_VERSION ART_MUS_FESTIVALES_VERSION { get; set; }
    }
}
