//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD
    {
        public ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD()
        {
            this.ART_MUS_FESTIVALES_ENTIDADES_ALIADAS = new HashSet<ART_MUS_FESTIVALES_ENTIDADES_ALIADAS>();
        }
    
        public int ID { get; set; }
        public string NATURALEZA { get; set; }
    
        public virtual ICollection<ART_MUS_FESTIVALES_ENTIDADES_ALIADAS> ART_MUS_FESTIVALES_ENTIDADES_ALIADAS { get; set; }
    }
}
