//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_FORMULARIOS_LISTAS_ELEMENTOS
    {
        public decimal FLE_ID { get; set; }
        public string FLE_ETIQUETA { get; set; }
        public string FLE_VALOR { get; set; }
        public decimal FLI_ID { get; set; }
    
        public virtual ART_ME_FORMULARIOS_LISTAS ART_ME_FORMULARIOS_LISTAS { get; set; }
    }
}
