//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_DOTACION_INSTRUMENTOS
    {
        public int Id { get; set; }
        public int DotacionId { get; set; }
        public int InstrumentoId { get; set; }
        public int PrioridadId { get; set; }
        public int Cantidad { get; set; }
    
        public virtual ART_MUSICA_DOTACION ART_MUSICA_DOTACION { get; set; }
    }
}
