//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ENTIDAD_TIPOS_INTERNET
    {
        public int ID { get; set; }
        public int TIPOS_INTERNET_ID { get; set; }
        public decimal ENT_ID { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ART_MUSICA_TIPOS_INTERNET ART_MUSICA_TIPOS_INTERNET { get; set; }
    }
}
