//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ARTISTAS_CELEBRA
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Enlace { get; set; }
        public string Contacto { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public int Orden { get; set; }
        public Nullable<bool> EsGrupo { get; set; }
        public int CantidadMiembros { get; set; }
        public byte[] Imagen { get; set; }
        public string Resena { get; set; }
        public int ProcesoId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaPresentacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int EventoId { get; set; }
        public int CategoriaId { get; set; }
    
        public virtual ART_MUSICA_CELEBRA_CATEGORIA ART_MUSICA_CELEBRA_CATEGORIA { get; set; }
        public virtual ART_MUSICA_PROCESO_FORMACION ART_MUSICA_PROCESO_FORMACION { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ART_MUSICA_EVENTOS ART_MUSICA_EVENTOS { get; set; }
    }
}
