//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_ENTIDAD_FORMACION
    {
        public ART_MUSICA_ENTIDAD_FORMACION()
        {
            this.ART_MUSICA_PRACTICA_MUSICAL = new HashSet<ART_MUSICA_PRACTICA_MUSICAL>();
        }
    
        public decimal ENT_ID { get; set; }
        public string ENT_PROCESOS_FORMACION { get; set; }
        public bool ENT_PRACTICAS_MUSICALES_ORIENTADAS_MUSICO { get; set; }
        public bool ENT_TALLERES_INDEPENDIENTES { get; set; }
        public bool ENT_PROGRAMAS_FORMULADOS_ESCRITO { get; set; }
        public bool ENT_FOMRACION_MUSICAL_PLAN_NAL_MUSICA_CONVIVENCIA { get; set; }
        public Nullable<int> INICIACION_DURACION_PROMEDIO_MESES { get; set; }
        public Nullable<int> INICIACION_POBLACION_MENOR_6_ANOS { get; set; }
        public Nullable<int> INICIACION_POBLACION_MENOR_11_ANOS { get; set; }
        public Nullable<int> INICIACION_POBLACION_MENOR_18_ANOS { get; set; }
        public Nullable<int> INICIACION_POBLACION_MENOR_26_ANOS { get; set; }
        public Nullable<int> INICIACION_POBLACION_MENOR_60_ANOS { get; set; }
        public Nullable<int> INICIACION_POBLACION_MAYOR_60_ANOS { get; set; }
        public Nullable<int> INICIACION_INTENSIDAD_HORAS_SEMANAL { get; set; }
        public string INICIACION_OBSERVACIONES { get; set; }
        public Nullable<int> BASICO_DURACION_PROMEDIO_MESES { get; set; }
        public Nullable<int> BASICO_POBLACION_MENOR_6_ANOS { get; set; }
        public Nullable<int> BASICO_POBLACION_MENOR_11_ANOS { get; set; }
        public Nullable<int> BASICO_POBLACION_MENOR_18_ANOS { get; set; }
        public Nullable<int> BASICO_POBLACION_MENOR_26_ANOS { get; set; }
        public Nullable<int> BASICO_POBLACION_MENOR_60_ANOS { get; set; }
        public Nullable<int> BASICO_POBLACION_MAYOR_60_ANOS { get; set; }
        public Nullable<int> BASICO_INTENSIDAD_HORAS_SEMANAL { get; set; }
        public string BASICO_OBSERVACIONES { get; set; }
        public Nullable<int> MEDIO_DURACION_PROMEDIO_MESES { get; set; }
        public Nullable<int> MEDIO_POBLACION_MENOR_6_ANOS { get; set; }
        public Nullable<int> MEDIO_POBLACION_MENOR_11_ANOS { get; set; }
        public Nullable<int> MEDIO_POBLACION_MENOR_18_ANOS { get; set; }
        public Nullable<int> MEDIO_POBLACION_MENOR_26_ANOS { get; set; }
        public Nullable<int> MEDIO_POBLACION_MENOR_60_ANOS { get; set; }
        public Nullable<int> MEDIO_POBLACION_MAYOR_60_ANOS { get; set; }
        public Nullable<int> MEDIO_INTENSIDAD_HORAS_SEMANAL { get; set; }
        public string MEDIO_OBSERVACIONES { get; set; }
        public Nullable<int> CURSO_DURACION_PROCURSO_SEMANA { get; set; }
        public Nullable<int> CURSO_POBLACION_MENOR_6_ANOS { get; set; }
        public Nullable<int> CURSO_POBLACION_MENOR_11_ANOS { get; set; }
        public Nullable<int> CURSO_POBLACION_MENOR_18_ANOS { get; set; }
        public Nullable<int> CURSO_POBLACION_MENOR_26_ANOS { get; set; }
        public Nullable<int> CURSO_POBLACION_MENOR_60_ANOS { get; set; }
        public Nullable<int> CURSO_POBLACION_MAYOR_60_ANOS { get; set; }
        public Nullable<int> CURSO_INTENSIDAD_HORAS_SEMANAL { get; set; }
        public string CURSO_OBSERVACIONES { get; set; }
        public Nullable<int> PEDAGOGIAS_DURACION_PROPEDAGOGIAS_SEMANA { get; set; }
        public Nullable<int> PEDAGOGIAS_POBLACION_MENOR_6_ANOS { get; set; }
        public Nullable<int> PEDAGOGIAS_POBLACION_MENOR_11_ANOS { get; set; }
        public Nullable<int> PEDAGOGIAS_POBLACION_MENOR_18_ANOS { get; set; }
        public Nullable<int> PEDAGOGIAS_POBLACION_MENOR_26_ANOS { get; set; }
        public Nullable<int> PEDAGOGIAS_POBLACION_MENOR_60_ANOS { get; set; }
        public Nullable<int> PEDAGOGIAS_POBLACION_MAYOR_60_ANOS { get; set; }
        public Nullable<int> PEDAGOGIAS_INTENSIDAD_HORAS_SEMANAL { get; set; }
        public string PEDAGOGIAS_OBSERVACIONES { get; set; }
        public Nullable<int> TOTAL_INICACION_POBLACION { get; set; }
        public Nullable<int> TOTAL_BASICO_POBLACION { get; set; }
        public Nullable<int> TOTAL_MEDIO_POBLACION { get; set; }
        public Nullable<int> TOTAL_CURSOS_POBLACION { get; set; }
        public Nullable<int> TOTAL_PEDAGOGIA_POBLACION { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
        public virtual ICollection<ART_MUSICA_PRACTICA_MUSICAL> ART_MUSICA_PRACTICA_MUSICAL { get; set; }
    }
}
