//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_AGRUPACION
    {
        public ART_MUSICA_AGRUPACION()
        {
            this.ART_MUSICA_AGENTE_AGRUPACION = new HashSet<ART_MUSICA_AGENTE_AGRUPACION>();
            this.ART_MUSICA_AGRUPACION_GENEROS = new HashSet<ART_MUSICA_AGRUPACION_GENEROS>();
            this.ART_MUSICA_CONVOCATORIAS = new HashSet<ART_MUSICA_CONVOCATORIAS>();
            this.ART_MUSICA_ESCENARIOS = new HashSet<ART_MUSICA_ESCENARIOS>();
            this.ART_MUSICA_MOTIVO_HISTORICO = new HashSet<ART_MUSICA_MOTIVO_HISTORICO>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string CodigoPais { get; set; }
        public string CodigoMunicipio { get; set; }
        public string CodigoDepartamento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public byte[] Imagen { get; set; }
        public string CorreoElectronico { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string LinkPortafolio { get; set; }
        public int ArtMusicaUsuarioId { get; set; }
        public int EstadoId { get; set; }
        public decimal ArdId { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CodTipoDocumento { get; set; }
        public string Identificacion { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SedundoApellido { get; set; }
        public int TipoAgrupacionId { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public int NaturalezaId { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public Nullable<int> ARE_ID { get; set; }
    
        public virtual ICollection<ART_MUSICA_AGENTE_AGRUPACION> ART_MUSICA_AGENTE_AGRUPACION { get; set; }
        public virtual ART_MUSICA_ESTADOS ART_MUSICA_ESTADOS { get; set; }
        public virtual ART_MUSICA_NATURALEZA_AGRUPACION ART_MUSICA_NATURALEZA_AGRUPACION { get; set; }
        public virtual ART_MUSICA_TIPO_AGRUPACION ART_MUSICA_TIPO_AGRUPACION { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ICollection<ART_MUSICA_AGRUPACION_GENEROS> ART_MUSICA_AGRUPACION_GENEROS { get; set; }
        public virtual ICollection<ART_MUSICA_CONVOCATORIAS> ART_MUSICA_CONVOCATORIAS { get; set; }
        public virtual ICollection<ART_MUSICA_ESCENARIOS> ART_MUSICA_ESCENARIOS { get; set; }
        public virtual ICollection<ART_MUSICA_MOTIVO_HISTORICO> ART_MUSICA_MOTIVO_HISTORICO { get; set; }
    }
}
