//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_MODULO_SERVICIOS
    {
        public int Id { get; set; }
        public int TipoActorId { get; set; }
        public string TipoActor { get; set; }
        public Nullable<int> TipoServicioId { get; set; }
        public string NombreActor { get; set; }
        public Nullable<decimal> EscuelaId { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public Nullable<int> AgrupacionId { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public Nullable<int> TipoEventoId { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string CodMunicipio { get; set; }
        public string Municipio { get; set; }
        public string CodDepto { get; set; }
        public string Departamento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Contacto { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public byte[] Imagen { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioAprobadorId { get; set; }
        public Nullable<decimal> EventoSINICId { get; set; }
        public int EstadoId { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordenadas { get; set; }
        public Nullable<int> CodPais { get; set; }
        public string OtraCiudad { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public string PaginaWeb { get; set; }
    
        public virtual ART_MUSICA_PARAMETROS_SERVICIOS ART_MUSICA_PARAMETROS_SERVICIOS { get; set; }
        public virtual ART_MUSICA_PARAMETROS_SERVICIOS ART_MUSICA_PARAMETROS_SERVICIOS1 { get; set; }
        public virtual ART_MUSICA_PARAMETROS_SERVICIOS ART_MUSICA_PARAMETROS_SERVICIOS2 { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO { get; set; }
        public virtual ART_MUSICA_USUARIO ART_MUSICA_USUARIO1 { get; set; }
    }
}
