//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_VIDEOS_ESCUELAS
    {
        public decimal VID_ID { get; set; }
        public decimal ENT_ID { get; set; }
        public string VID_URL { get; set; }
        public string VID_DESCRIPCION { get; set; }
        public System.DateTime VID_FECHA_PUBLICACION { get; set; }
        public string VID_CLASIFICACION { get; set; }
    
        public virtual ART_ENTIDADES_ARTES ART_ENTIDADES_ARTES { get; set; }
    }
}
