//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_PARAMETROS_SERVICIOS
    {
        public ART_MUSICA_PARAMETROS_SERVICIOS()
        {
            this.ART_MUSICA_CONVOCATORIAS = new HashSet<ART_MUSICA_CONVOCATORIAS>();
            this.ART_MUSICA_PARTICIPACION = new HashSet<ART_MUSICA_PARTICIPACION>();
            this.ART_MUSICA_MODULO_SERVICIOS = new HashSet<ART_MUSICA_MODULO_SERVICIOS>();
            this.ART_MUSICA_MODULO_SERVICIOS1 = new HashSet<ART_MUSICA_MODULO_SERVICIOS>();
            this.ART_MUSICA_MODULO_SERVICIOS2 = new HashSet<ART_MUSICA_MODULO_SERVICIOS>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int CategoriaId { get; set; }
        public string Categoria { get; set; }
    
        public virtual ICollection<ART_MUSICA_CONVOCATORIAS> ART_MUSICA_CONVOCATORIAS { get; set; }
        public virtual ICollection<ART_MUSICA_PARTICIPACION> ART_MUSICA_PARTICIPACION { get; set; }
        public virtual ICollection<ART_MUSICA_MODULO_SERVICIOS> ART_MUSICA_MODULO_SERVICIOS { get; set; }
        public virtual ICollection<ART_MUSICA_MODULO_SERVICIOS> ART_MUSICA_MODULO_SERVICIOS1 { get; set; }
        public virtual ICollection<ART_MUSICA_MODULO_SERVICIOS> ART_MUSICA_MODULO_SERVICIOS2 { get; set; }
    }
}
