//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_GENEROS_MUSICALES
    {
        public ART_MUSICA_GENEROS_MUSICALES()
        {
            this.ART_MUSICA_AGENTE_GENEROS = new HashSet<ART_MUSICA_AGENTE_GENEROS>();
            this.ART_MUSICA_PRACTICA_GENERO = new HashSet<ART_MUSICA_PRACTICA_GENERO>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PadreId { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public int Nivel { get; set; }
    
        public virtual ICollection<ART_MUSICA_AGENTE_GENEROS> ART_MUSICA_AGENTE_GENEROS { get; set; }
        public virtual ART_MUSICA_GENEROS_MUSICALES ART_MUSICA_GENEROS_MUSICALES1 { get; set; }
        public virtual ART_MUSICA_GENEROS_MUSICALES ART_MUSICA_GENEROS_MUSICALES2 { get; set; }
        public virtual ICollection<ART_MUSICA_PRACTICA_GENERO> ART_MUSICA_PRACTICA_GENERO { get; set; }
    }
}
