//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_ME_FORMULARIOS_COLUMNAS
    {
        public ART_ME_FORMULARIOS_COLUMNAS()
        {
            this.ART_ME_FORMULARIOS_VALORES = new HashSet<ART_ME_FORMULARIOS_VALORES>();
            this.ART_MUSICA_FORMULARIO_ARCHIVOS = new HashSet<ART_MUSICA_FORMULARIO_ARCHIVOS>();
        }
    
        public decimal FCO_ID { get; set; }
        public string FCO_NOMBRE { get; set; }
        public string FCO_DESCRIPCION { get; set; }
        public string FCO_TIPODATO { get; set; }
        public string FCO_ESOBLIGATORIA { get; set; }
        public Nullable<decimal> FLI_ID { get; set; }
        public decimal FOR_ID { get; set; }
        public Nullable<int> FCO_ORDEN { get; set; }
        public Nullable<decimal> FSC_ID { get; set; }
    
        public virtual ART_ME_FORMULARIOS ART_ME_FORMULARIOS { get; set; }
        public virtual ART_ME_FORMULARIOS_LISTAS ART_ME_FORMULARIOS_LISTAS { get; set; }
        public virtual ART_ME_FORMULARIOS_SECCIONES ART_ME_FORMULARIOS_SECCIONES { get; set; }
        public virtual ICollection<ART_ME_FORMULARIOS_VALORES> ART_ME_FORMULARIOS_VALORES { get; set; }
        public virtual ICollection<ART_MUSICA_FORMULARIO_ARCHIVOS> ART_MUSICA_FORMULARIO_ARCHIVOS { get; set; }
    }
}
