//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_TIPO_VINCULACION
    {
        public ART_MUSICA_TIPO_VINCULACION()
        {
            this.ART_MUSICA_ENTIDAD_INSTITUCIONALIDAD = new HashSet<ART_MUSICA_ENTIDAD_INSTITUCIONALIDAD>();
        }
    
        public short ID_TIPO_VINCULACION { get; set; }
        public string DESCRIPCION_TIPO_VINCULACION { get; set; }
    
        public virtual ICollection<ART_MUSICA_ENTIDAD_INSTITUCIONALIDAD> ART_MUSICA_ENTIDAD_INSTITUCIONALIDAD { get; set; }
    }
}
