//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_MATERIAL_PEDAGOGICO
    {
        public ART_MUSICA_MATERIAL_PEDAGOGICO()
        {
            this.ART_MUSICA_ENTIDAD_INFRAESTRUCTURA = new HashSet<ART_MUSICA_ENTIDAD_INFRAESTRUCTURA>();
        }
    
        public short ART_MUS_MAT_PED_ID { get; set; }
        public string ART_MUS_MAT_PED_DESCRIPCION { get; set; }
    
        public virtual ICollection<ART_MUSICA_ENTIDAD_INFRAESTRUCTURA> ART_MUSICA_ENTIDAD_INFRAESTRUCTURA { get; set; }
    }
}
