//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_MUSICA_CONVOCATORIA_ACTORES
    {
        public int Id { get; set; }
        public int ConvocatoriaId { get; set; }
        public int ActorId { get; set; }
    
        public virtual ART_MUSICA_CONVOCATORIAS ART_MUSICA_CONVOCATORIAS { get; set; }
    }
}
