//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_ZONAS_GEOGRAFICAS
    {
        public BAS_ZONAS_GEOGRAFICAS()
        {
            this.ART_ENTIDAD_UBICACION = new HashSet<ART_ENTIDAD_UBICACION>();
            this.ART_INFRAESTRUCTURA_ENTIDADES = new HashSet<ART_INFRAESTRUCTURA_ENTIDADES>();
            this.ART_ME_USUARIOS = new HashSet<ART_ME_USUARIOS>();
            this.ART_ME_USUARIOS1 = new HashSet<ART_ME_USUARIOS>();
            this.ART_ME_PERFILES = new HashSet<ART_ME_PERFILES>();
            this.ART_MUSICA_WS_USUARIO = new HashSet<ART_MUSICA_WS_USUARIO>();
            this.ART_MUS_LOCALIZACIONXVERSION = new HashSet<ART_MUS_LOCALIZACIONXVERSION>();
            this.ART_MUS_ZONAXREGION_OCAD = new HashSet<ART_MUS_ZONAXREGION_OCAD>();
        }
    
        public string ZON_ID { get; set; }
        public string ZON_NOMBRE { get; set; }
        public string ZON_PADRE_ID { get; set; }
        public Nullable<int> ZON_POBLACION { get; set; }
        public string x { get; set; }
        public Nullable<double> ZON_LATITUD { get; set; }
        public Nullable<double> ZON_LONGITUD { get; set; }
        public Nullable<bool> EsCorrimiento { get; set; }
        public string ZON_PREFIJO_DOCUMENTO { get; set; }
        public Nullable<int> ZON_CONSECUTIVO_DOCUMENTO { get; set; }
    
        public virtual ICollection<ART_ENTIDAD_UBICACION> ART_ENTIDAD_UBICACION { get; set; }
        public virtual ICollection<ART_INFRAESTRUCTURA_ENTIDADES> ART_INFRAESTRUCTURA_ENTIDADES { get; set; }
        public virtual ICollection<ART_ME_USUARIOS> ART_ME_USUARIOS { get; set; }
        public virtual ICollection<ART_ME_USUARIOS> ART_ME_USUARIOS1 { get; set; }
        public virtual ICollection<ART_ME_PERFILES> ART_ME_PERFILES { get; set; }
        public virtual ICollection<ART_MUSICA_WS_USUARIO> ART_MUSICA_WS_USUARIO { get; set; }
        public virtual ICollection<ART_MUS_LOCALIZACIONXVERSION> ART_MUS_LOCALIZACIONXVERSION { get; set; }
        public virtual ICollection<ART_MUS_ZONAXREGION_OCAD> ART_MUS_ZONAXREGION_OCAD { get; set; }
    }
}
