//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_TIPOS_DOCUMENTOS_IDENTIDAD
    {
        public BAS_TIPOS_DOCUMENTOS_IDENTIDAD()
        {
            this.ART_ENTIDADES_ARTES = new HashSet<ART_ENTIDADES_ARTES>();
        }
    
        public decimal DOC_ID { get; set; }
        public string DOC_NOMBRE { get; set; }
        public string DOC_ACTIVO { get; set; }
        public string CODIGO { get; set; }
    
        public virtual ICollection<ART_ENTIDADES_ARTES> ART_ENTIDADES_ARTES { get; set; }
    }
}
