//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_DEPARTAMENTOS_ZONA_PADRE
    {
        public string ZON_PADRE_ID { get; set; }
        public string ZON_PADRE_NOMBRE { get; set; }
    
        public virtual BAS_DEPARTAMENTOS_ZONA_PADRE BAS_DEPARTAMENTOS_ZONA_PADRE1 { get; set; }
        public virtual BAS_DEPARTAMENTOS_ZONA_PADRE BAS_DEPARTAMENTOS_ZONA_PADRE2 { get; set; }
    }
}
