//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.SIPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_ZONAS_PAISES
    {
        public BAS_ZONAS_PAISES()
        {
            this.ART_ENTIDAD_UBICACION = new HashSet<ART_ENTIDAD_UBICACION>();
            this.ART_INFRAESTRUCTURA_ENTIDADES = new HashSet<ART_INFRAESTRUCTURA_ENTIDADES>();
        }
    
        public int ZOP_ID { get; set; }
        public string ZOP_NOMBRE { get; set; }
        public string ZOP_CODIGO_INTERNET { get; set; }
    
        public virtual ICollection<ART_ENTIDAD_UBICACION> ART_ENTIDAD_UBICACION { get; set; }
        public virtual ICollection<ART_INFRAESTRUCTURA_ENTIDADES> ART_INFRAESTRUCTURA_ENTIDADES { get; set; }
    }
}
