//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.Aplicacion.ServicioEstimulos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModalidadDTO", Namespace="http://schemas.datacontract.org/2004/07/WsResultadosEstimulos")]
    [System.SerializableAttribute()]
    public partial class ModalidadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreModalidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoModalidad {
            get {
                return this.CodigoModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoModalidadField, value) != true)) {
                    this.CodigoModalidadField = value;
                    this.RaisePropertyChanged("CodigoModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreModalidad {
            get {
                return this.NombreModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreModalidadField, value) != true)) {
                    this.NombreModalidadField = value;
                    this.RaisePropertyChanged("NombreModalidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoInscripcionDTO", Namespace="http://schemas.datacontract.org/2004/07/WsResultadosEstimulos")]
    [System.SerializableAttribute()]
    public partial class EstadoInscripcionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEstado {
            get {
                return this.CodigoEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEstadoField, value) != true)) {
                    this.CodigoEstadoField = value;
                    this.RaisePropertyChanged("CodigoEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstado {
            get {
                return this.NombreEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstadoField, value) != true)) {
                    this.NombreEstadoField = value;
                    this.RaisePropertyChanged("NombreEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConvocatoriasDTO", Namespace="http://schemas.datacontract.org/2004/07/WsResultadosEstimulos.DTO")]
    [System.SerializableAttribute()]
    public partial class ConvocatoriasDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoConvocatoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreConvocatoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoConvocatoria {
            get {
                return this.CodigoConvocatoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoConvocatoriaField, value) != true)) {
                    this.CodigoConvocatoriaField = value;
                    this.RaisePropertyChanged("CodigoConvocatoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreConvocatoria {
            get {
                return this.NombreConvocatoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreConvocatoriaField, value) != true)) {
                    this.NombreConvocatoriaField = value;
                    this.RaisePropertyChanged("NombreConvocatoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadosDTO", Namespace="http://schemas.datacontract.org/2004/07/WsResultadosEstimulos.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultadosDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CausalRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreConvocatoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreParticipanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroRadicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParticipanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeudonimoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((this.AnioField.Equals(value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CausalRechazo {
            get {
                return this.CausalRechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.CausalRechazoField, value) != true)) {
                    this.CausalRechazoField = value;
                    this.RaisePropertyChanged("CausalRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoMunicipio {
            get {
                return this.CodigoMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoMunicipioField, value) != true)) {
                    this.CodigoMunicipioField = value;
                    this.RaisePropertyChanged("CodigoMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaNacimientoField, value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipio {
            get {
                return this.MunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                    this.MunicipioField = value;
                    this.RaisePropertyChanged("Municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreConvocatoria {
            get {
                return this.NombreConvocatoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreConvocatoriaField, value) != true)) {
                    this.NombreConvocatoriaField = value;
                    this.RaisePropertyChanged("NombreConvocatoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstado {
            get {
                return this.NombreEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstadoField, value) != true)) {
                    this.NombreEstadoField = value;
                    this.RaisePropertyChanged("NombreEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreModalidad {
            get {
                return this.NombreModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreModalidadField, value) != true)) {
                    this.NombreModalidadField = value;
                    this.RaisePropertyChanged("NombreModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreParticipante {
            get {
                return this.NombreParticipanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreParticipanteField, value) != true)) {
                    this.NombreParticipanteField = value;
                    this.RaisePropertyChanged("NombreParticipante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProyecto {
            get {
                return this.NombreProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProyectoField, value) != true)) {
                    this.NombreProyectoField = value;
                    this.RaisePropertyChanged("NombreProyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroRadicacion {
            get {
                return this.NumeroRadicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroRadicacionField, value) != true)) {
                    this.NumeroRadicacionField = value;
                    this.RaisePropertyChanged("NumeroRadicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Participante {
            get {
                return this.ParticipanteField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipanteField, value) != true)) {
                    this.ParticipanteField = value;
                    this.RaisePropertyChanged("Participante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resolucion {
            get {
                return this.ResolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolucionField, value) != true)) {
                    this.ResolucionField = value;
                    this.RaisePropertyChanged("Resolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seudonimo {
            get {
                return this.SeudonimoField;
            }
            set {
                if ((object.ReferenceEquals(this.SeudonimoField, value) != true)) {
                    this.SeudonimoField = value;
                    this.RaisePropertyChanged("Seudonimo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mctucano:28827/", ConfigurationName="ServicioEstimulos.IServicioResultadoEstimulos")]
    public interface IServicioResultadoEstimulos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/DoWork", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/DoWork", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetAnios", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetAniosResponse")]
        short[] GetAnios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetAnios", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetAniosResponse")]
        System.Threading.Tasks.Task<short[]> GetAniosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetModalidades", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetModalidadesResponse")]
        SM.Aplicacion.ServicioEstimulos.ModalidadDTO[] GetModalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetModalidades", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetModalidadesResponse")]
        System.Threading.Tasks.Task<SM.Aplicacion.ServicioEstimulos.ModalidadDTO[]> GetModalidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetEstadoInscripcion", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetEstadoInscripcionResponse")]
        SM.Aplicacion.ServicioEstimulos.EstadoInscripcionDTO[] GetEstadoInscripcion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetEstadoInscripcion", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetEstadoInscripcionResponse")]
        System.Threading.Tasks.Task<SM.Aplicacion.ServicioEstimulos.EstadoInscripcionDTO[]> GetEstadoInscripcionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetConvocatorias", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetConvocatoriasResponse")]
        SM.Aplicacion.ServicioEstimulos.ConvocatoriasDTO[] GetConvocatorias(string anio, string modalidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetConvocatorias", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetConvocatoriasResponse")]
        System.Threading.Tasks.Task<SM.Aplicacion.ServicioEstimulos.ConvocatoriasDTO[]> GetConvocatoriasAsync(string anio, string modalidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetResultados", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetResultadosResponse")]
        SM.Aplicacion.ServicioEstimulos.ResultadosDTO[] GetResultados(string anio, string modalidad, string convocatoria, string estadoinscripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mctucano:28827/IServicioResultadoEstimulos/GetResultados", ReplyAction="http://mctucano:28827/IServicioResultadoEstimulos/GetResultadosResponse")]
        System.Threading.Tasks.Task<SM.Aplicacion.ServicioEstimulos.ResultadosDTO[]> GetResultadosAsync(string anio, string modalidad, string convocatoria, string estadoinscripcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioResultadoEstimulosChannel : SM.Aplicacion.ServicioEstimulos.IServicioResultadoEstimulos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioResultadoEstimulosClient : System.ServiceModel.ClientBase<SM.Aplicacion.ServicioEstimulos.IServicioResultadoEstimulos>, SM.Aplicacion.ServicioEstimulos.IServicioResultadoEstimulos {
        
        public ServicioResultadoEstimulosClient() {
        }
        
        public ServicioResultadoEstimulosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioResultadoEstimulosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResultadoEstimulosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResultadoEstimulosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public short[] GetAnios() {
            return base.Channel.GetAnios();
        }
        
        public System.Threading.Tasks.Task<short[]> GetAniosAsync() {
            return base.Channel.GetAniosAsync();
        }
        
        public SM.Aplicacion.ServicioEstimulos.ModalidadDTO[] GetModalidades() {
            return base.Channel.GetModalidades();
        }
        
        public System.Threading.Tasks.Task<SM.Aplicacion.ServicioEstimulos.ModalidadDTO[]> GetModalidadesAsync() {
            return base.Channel.GetModalidadesAsync();
        }
        
        public SM.Aplicacion.ServicioEstimulos.EstadoInscripcionDTO[] GetEstadoInscripcion() {
            return base.Channel.GetEstadoInscripcion();
        }
        
        public System.Threading.Tasks.Task<SM.Aplicacion.ServicioEstimulos.EstadoInscripcionDTO[]> GetEstadoInscripcionAsync() {
            return base.Channel.GetEstadoInscripcionAsync();
        }
        
        public SM.Aplicacion.ServicioEstimulos.ConvocatoriasDTO[] GetConvocatorias(string anio, string modalidad) {
            return base.Channel.GetConvocatorias(anio, modalidad);
        }
        
        public System.Threading.Tasks.Task<SM.Aplicacion.ServicioEstimulos.ConvocatoriasDTO[]> GetConvocatoriasAsync(string anio, string modalidad) {
            return base.Channel.GetConvocatoriasAsync(anio, modalidad);
        }
        
        public SM.Aplicacion.ServicioEstimulos.ResultadosDTO[] GetResultados(string anio, string modalidad, string convocatoria, string estadoinscripcion) {
            return base.Channel.GetResultados(anio, modalidad, convocatoria, estadoinscripcion);
        }
        
        public System.Threading.Tasks.Task<SM.Aplicacion.ServicioEstimulos.ResultadosDTO[]> GetResultadosAsync(string anio, string modalidad, string convocatoria, string estadoinscripcion) {
            return base.Channel.GetResultadosAsync(anio, modalidad, convocatoria, estadoinscripcion);
        }
    }
}
