//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.LibreriaRecursos.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SM.LibreriaRecursos.Recursos.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2019.
        /// </summary>
        internal static string Celebra_Ano_Evento {
            get {
                return ResourceManager.GetString("Celebra_Ano_Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2019-11-24.
        /// </summary>
        internal static string Celebra_Fecha_Evento {
            get {
                return ResourceManager.GetString("Celebra_Fecha_Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADMIN.
        /// </summary>
        internal static string SIMUS_codigo_Admin {
            get {
                return ResourceManager.GetString("SIMUS_codigo_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 13.
        /// </summary>
        internal static string SIMUS_Codigo_Danza {
            get {
                return ResourceManager.GetString("SIMUS_Codigo_Danza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 15.
        /// </summary>
        internal static string SIMUS_Codigo_Musica {
            get {
                return ResourceManager.GetString("SIMUS_Codigo_Musica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o contraseña invalida..
        /// </summary>
        internal static string SIMUS_Contrasena_Invalida {
            get {
                return ResourceManager.GetString("SIMUS_Contrasena_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro creado exitosamente.
        /// </summary>
        internal static string SIMUS_Creacion_Exitosa {
            get {
                return ResourceManager.GetString("SIMUS_Creacion_Exitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Danza.
        /// </summary>
        internal static string SIMUS_Danza {
            get {
                return ResourceManager.GetString("SIMUS_Danza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;La escuela municipal de música no se encuentra creada en SIMUS.  Para continuar con el proceso debe crearla&quot;.
        /// </summary>
        internal static string SIMUS_Mensaje_Escuela {
            get {
                return ResourceManager.GetString("SIMUS_Mensaje_Escuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o de mincultura invalido..
        /// </summary>
        internal static string SIMUS_mincutura_invalido {
            get {
                return ResourceManager.GetString("SIMUS_mincutura_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Música.
        /// </summary>
        internal static string SIMUS_Musica {
            get {
                return ResourceManager.GetString("SIMUS_Musica", resourceCulture);
            }
        }
    }
}
