USE [SIPA]
GO

/****** Object:  Table [dbo].[ART_MUSICA_TIPO_AGRUPACION]    Script Date: 10/12/2015 3:58:27 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_TIPO_AGRUPACION](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_TIPO_AGRUPACION] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_NATURALEZA_AGRUPACION](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_NATURALEZA_AGRUPACION] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[ART_MUSICA_AGRUPACION]    Script Date: 10/12/2015 3:48:04 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_AGRUPACION](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](200) NOT NULL,
	[CodigoPais] [varchar](10) NOT NULL,
	[CodigoMunicipio] [varchar](5)  NULL,
	[CodigoDepartamento] [varchar](5)  NULL,
	[Direccion] [varchar](200) NOT NULL,
	[Telefono] [varchar](50) NOT NULL,
	[Imagen] [image] NULL,
	[CorreoElectronico] [varchar](200) NOT NULL,
	[Latitud] [varchar](20) NULL,
	[Longitud] [varchar](20) NULL,
	[LinkPortafolio] [varchar](200) NULL,
	[ArtMusicaUsuarioId] [int] NOT NULL,
	[EstadoId] [int] NOT NULL,
	[ArdId] [numeric](18, 0) NOT NULL,
	[FechaActualizacion] [date] NOT NULL,
	[FechaCreacion] [date] NOT NULL,
	[Descripcion] [varchar](max) NULL,
	[CodTipoDocumento] [int] NOT NULL,
	[Identificacion] [varchar](20) NOT NULL,
	[PrimerNombre] [varchar](50) NOT NULL,
	[SegundoNombre] [varchar](50) NULL,
	[PrimerApellido] [varchar](50) NOT NULL,
	[SedundoApellido] [varchar](50) NULL,
	[TipoAgrupacionId] [int] not NULL,
	[AgenteId] [int] not NULL,
	[NaturalezaId] [int] not NULL,
 CONSTRAINT [PK_ART_MUSICA_AGRUPACION] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_AREA_ARTISTICAS] FOREIGN KEY([ArdId])
REFERENCES [dbo].[ART_AREA_ARTISTICAS] ([ARD_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_AREA_ARTISTICAS]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_ESTADOS] FOREIGN KEY([EstadoId])
REFERENCES [dbo].[ART_MUSICA_ESTADOS] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_ESTADOS]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_USUARIO] FOREIGN KEY([ArtMusicaUsuarioId])
REFERENCES [dbo].[ART_MUSICA_USUARIO] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_USUARIO]
GO


ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_TIPO_AGRUPACION] FOREIGN KEY([TipoAgrupacionId])
REFERENCES [dbo].[ART_MUSICA_TIPO_AGRUPACION] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_TIPO_AGRUPACION]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_AGENTE] FOREIGN KEY(AgenteId)
REFERENCES [dbo].[ART_MUSICA_AGENTE] ([ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_AGENTE]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_NATURALEZA_AGRUPACION] FOREIGN KEY(NaturalezaId)
REFERENCES [dbo].ART_MUSICA_NATURALEZA_AGRUPACION ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_NATURALEZA_AGRUPACION]
GO


/****** Object:  Table [dbo].[ART_MUSICA_AGENTE_AGRUPACION]    Script Date: 15/12/2015 8:44:38 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ART_MUSICA_AGENTE_AGRUPACION](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AgrupacionId] [int] NOT NULL,
	[AgenteId] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_AGENTE_AGRUPACION] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGENTE_AGRUPACION_ART_MUSICA_AGENTE] FOREIGN KEY([AgenteId])
REFERENCES [dbo].[ART_MUSICA_AGENTE] ([ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGENTE_AGRUPACION_ART_MUSICA_AGENTE]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGENTE_AGRUPACION_ART_MUSICA_AGRUPACION] FOREIGN KEY([AgrupacionId])
REFERENCES [dbo].[ART_MUSICA_AGRUPACION] ([Id])
GO

/****** Object:  Table [dbo].[ART_MUSICA_AGENTE_GENEROS]    Script Date: 16/12/2015 6:51:48 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ART_MUSICA_AGRUPACION_GENEROS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AgrupacionId] [int] NOT NULL,
	[GeneroId] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_AGRUPACION_GENEROS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION_GENEROS]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_GENEROS_ART_MUSICA_GENEROS_MUSICALES] FOREIGN KEY([GeneroId])
REFERENCES [dbo].[ART_MUSICA_GENEROS_MUSICALES] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION_GENEROS] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_GENEROS_ART_MUSICA_GENEROS_MUSICALES]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION_GENEROS]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_GENEROS_ART_MUSICA_AGRUPACION] FOREIGN KEY([AgrupacionId])
REFERENCES [dbo].[ART_MUSICA_AGRUPACION] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION_GENEROS] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_GENEROS_ART_MUSICA_AGRUPACION]
GO


