USE [SIPA]
GO
/****** Object:  StoredProcedure [dbo].[ART_ME_ART_ENTIDADES_ARTES_ESCUELAS_VALORES_CATEGORIZACION_ObtenerPorENT_ID]    Script Date: 06/10/2015 11:44:10 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE ART_MUSICA_VALORES_CATEGORIZACION (
	@ENT_ID numeric(18, 0)
)
AS

SET NOCOUNT ON

SELECT C.ID_FACTOR AS Id,
       C.DESCRIPCION_FACTOR as Descripcion,
	   Isnull(C.ID_FACTOR_PADRE, 0) as PadreId,
	   C.PORCENTAJE_FACTOR as Porcentaje,
	   E.VALOR as Valor
FROM ART_MUSICA_FACTOR_CATEGORIZACION C
LEFT JOIN ART_ENTIDADES_ARTES_ESCUELAS_VALORES_CATEGORIZACION E ON C.ID_FACTOR = E.ID_FACTOR
WHERE E.ENT_ID = @ENT_ID