USE [SIPA]
GO

/****** Object:  Table [dbo].[ART_MUSICA_ENTIDAD_TIPOS_INTERNET]    Script Date: 04/08/2015 3:37:17 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOS_INTERNET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TIPOS_INTERNET_ID] [int] NOT NULL,
	[ENT_ID] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_ENTIDAD_TIPOS_INTERNET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOS_INTERNET]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ENTIDAD_TIPOS_INTERNET_ART_ENTIDADES_ARTES] FOREIGN KEY([ENT_ID])
REFERENCES [dbo].[ART_ENTIDADES_ARTES] ([ENT_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOS_INTERNET] CHECK CONSTRAINT [FK_ART_MUSICA_ENTIDAD_TIPOS_INTERNET_ART_ENTIDADES_ARTES]
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOS_INTERNET]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ENTIDAD_TIPOS_INTERNET_ART_MUSICA_TIPOS_INTERNET] FOREIGN KEY([TIPOS_INTERNET_ID])
REFERENCES [dbo].[ART_MUSICA_TIPOS_INTERNET] ([ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOS_INTERNET] CHECK CONSTRAINT [FK_ART_MUSICA_ENTIDAD_TIPOS_INTERNET_ART_MUSICA_TIPOS_INTERNET]
GO


