

INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Compositor(a)',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Intérprete',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Director(a)',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Formador(a)',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Gestor(a)',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Investigador(a)',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Crítico(a)',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Técnico(a)',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Arreglista',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Autor',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Ingeniero de Luces',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Ingeniero de Sonido',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Productor Artístico',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Diseñador',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Editor',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Manager',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Lhutier',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Consumidor',1, 1)
INSERT INTO ART_MUSICA_OFICIOS VALUES (	'Fan',1, 1)

SELECT * FROM ART_MUSICA_TIPO_ENTIDAD


SELECT * FROM ART_MUSICA_TIPO_AGRUPACION


INSERT INTO ART_MUSICA_TIPO_AGRUPACION VALUES ('Coros')
INSERT INTO ART_MUSICA_TIPO_AGRUPACION VALUES ('Agrupaciones de Música Tradicional')
INSERT INTO ART_MUSICA_TIPO_AGRUPACION VALUES ('Agrupaciones de Música Popular Urbana')
INSERT INTO ART_MUSICA_TIPO_AGRUPACION VALUES ('Agrupaciones de Música Académica')





INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Formación Formal', 'FF')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Formación No Formal', 'FN')

INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Editora', 'ED')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Empresa Fonográfica', 'EF')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Editora', 'ED')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Empresa de Construcción y Reparación de Instrumentos', 'CR')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Productora de Eventos', 'PE')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Representación de Artistas', 'RA')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Distribuidora', 'DA')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Asociaciones', 'AS')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Redes', 'Re')