
CREATE PROCEDURE [dbo].[ART_MUSICA_REPORTE_ESCUELA_DPTO] AS

SET NOCOUNT ON
select DPTO.ZON_ID AS Id, DPTO.ZON_NOMBRE as Nombre, COUNT(*) as Value from 
ART_ENTIDADES_ARTES E,
ART_ENTIDAD_UBICACION  U, 
BAS_ZONAS_GEOGRAFICAS Z,
BAS_ZONAS_GEOGRAFICAS DPTO
where E.ent_tipo = 'E' AND E.ENT_ID=U.ENT_ID
AND E.ENT_ESTADO = 'E' AND DPTO.ZON_ID=Z.ZON_PADRE_ID
AND U.ZON_ID = Z.ZON_ID 
GROUP BY DPTO.ZON_ID,DPTO.ZON_NOMBRE
GO






CREATE PROCEDURE [dbo].[ART_MUSICA_REPORTE_ESCUELA_TIPO] AS
SET NOCOUNT ON
SELECT  NULL AS Id, ISNULL(J.ENT_NATURALEZA,'NO REPORTADO') as Nombre, COUNT(*) as Value 
FROM ART_ENTIDADES_ARTES E
LEFT JOIN ART_ENTIDAD_NATURALEZA_JURIDICA J ON E.ENT_ID =J.ENT_ID
where E.ent_tipo = 'E'
AND E.ENT_ESTADO = 'E'
GROUP BY J.ENT_NATURALEZA
GO





CREATE PROCEDURE [dbo].[ART_MUSICA_REPORTE_ESCUELA_PRAC_MUSICA] AS

SET NOCOUNT ON
  SELECT convert(varchar,M.ART_MUS_PRAC_MUS_ID) AS Id, isnull(M.ART_MUS_PRAC_MUS_DESCRIPCION,'No definida') as Nombre,COUNT(*) as Value
  FROM ART_ENTIDADES_ARTES E
  INNER JOIN ART_MUSICA_PRAC_MUS_ENT_FORMACION F ON E.ENT_ID = F.ENT_ID
  INNER JOIN ART_MUSICA_PRACTICA_MUSICAL M ON F.ART_MUS_PRAC_MUS_ID = M.ART_MUS_PRAC_MUS_ID
  where E.ent_tipo = 'E'
AND E.ENT_ESTADO = 'E'
  GROUP BY M.ART_MUS_PRAC_MUS_ID, M.ART_MUS_PRAC_MUS_DESCRIPCION
  GO