USE [SIPA]
GO

/****** Object:  Table [dbo].[ART_MUSICA_USUARIO]    Script Date: 20/10/2015 10:52:18 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_USUARIO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdUserRSS] [varchar](100) NULL,
	[TipoRSS] [nchar](20) NULL,
	[Email] [varchar](50) NOT NULL,
	[Identificacion] [varchar](50) NULL,
	[CodTipoDocumento] [varchar](50) NULL,
	[PrimerNombre] [varchar](50) NULL,
	[SegundoNombre] [varchar](50) NULL,
	[PrimerApellido] [varchar](50) NULL,
	[CodPais] [varchar](50) NULL,
	[CodDpto] [varchar](50) NULL,
	[CodMunicipio] [varchar](50) NULL,
	[Sexo] [nchar](10) NULL,
	[esUsuarioInterno] [bit] NULL,
	[esActivo] [bit] NULL,
	[FechaCreacion] [datetime] NOT NULL,
	[FechaModificacion] [datetime] NULL,
	[Imagen] [varchar](300) NULL,
	[Contraseña] [varchar](50) NULL,
	[ImagenUsuario] [image] NULL,
 CONSTRAINT [PK_ART_USUARIO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/* TABLA ROLES*/
CREATE TABLE [dbo].[ART_MUSICA_ROL](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [nvarchar](10) NULL,
	[Nombre] [nvarchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
 CONSTRAINT [PK_Rol] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/* TABLA RECURSOS*/

CREATE TABLE [dbo].[ART_MUSICA_RECURSO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [nchar](10) NULL,
	[IdPadre] [int] NULL,
	[Estado] [bit] NULL,
	[Descripcion] [nvarchar](50) NULL,
	[Ruta] [nvarchar](50) NULL,
	[Tipo] [nvarchar](50) NULL,
	[Nombre] [nvarchar](50) NULL,
	[Titulo] [nvarchar](50) NULL,
	[estilo] [nvarchar](50) NULL,
 CONSTRAINT [PK_Recurso] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


/* TABLA ROL RECURSO*/

CREATE TABLE [dbo].[ART_MUSICA_ROL_RECURSO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RolId] [int] NULL,
	[RecId] [int] NULL,
	[esActivo] [bit] NULL,
	[Fecha] [datetime] NULL,
	[NumMenu] [int] NOT NULL,
	[Orden] [int] NULL,
 CONSTRAINT [PK_RolesRecurso] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ART_MUSICA_ROL_RECURSO]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ROL_RECURSO_ART_MUSICA_RECURSO] FOREIGN KEY([RecId])
REFERENCES [dbo].[ART_MUSICA_RECURSO] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ROL_RECURSO] CHECK CONSTRAINT [FK_ART_MUSICA_ROL_RECURSO_ART_MUSICA_RECURSO]
GO

ALTER TABLE [dbo].[ART_MUSICA_ROL_RECURSO]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ROL_RECURSO_ART_MUSICA_ROL] FOREIGN KEY([RolId])
REFERENCES [dbo].[ART_MUSICA_ROL] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ROL_RECURSO] CHECK CONSTRAINT [FK_ART_MUSICA_ROL_RECURSO_ART_MUSICA_ROL]
GO


/* TABLA USUARIO ROL*/

CREATE TABLE [dbo].[ART_MUSICA_USUARIO_ROL](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleId] [int] NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_UsuarioRol] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ART_MUSICA_USUARIO_ROL]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_USUARIO_ROL_ART_MUSICA_ROL] FOREIGN KEY([RoleId])
REFERENCES [dbo].[ART_MUSICA_ROL] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_USUARIO_ROL] CHECK CONSTRAINT [FK_ART_MUSICA_USUARIO_ROL_ART_MUSICA_ROL]
GO

ALTER TABLE [dbo].[ART_MUSICA_USUARIO_ROL]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_USUARIO_ROL_ART_MUSICA_USUARIO] FOREIGN KEY([UserId])
REFERENCES [dbo].[ART_MUSICA_USUARIO] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_USUARIO_ROL] CHECK CONSTRAINT [FK_ART_MUSICA_USUARIO_ROL_ART_MUSICA_USUARIO]
GO


/* AGENTES*/



USE [SIPA]
GO

/****** Object:  Table [dbo].[ART_MUSICA_USUARIO]    Script Date: 20/10/2015 10:52:18 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_USUARIO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdUserRSS] [varchar](100) NULL,
	[TipoRSS] [nchar](20) NULL,
	[Email] [varchar](50) NOT NULL,
	[Identificacion] [varchar](50) NULL,
	[CodTipoDocumento] [varchar](50) NULL,
	[PrimerNombre] [varchar](50) NULL,
	[SegundoNombre] [varchar](50) NULL,
	[PrimerApellido] [varchar](50) NULL,
	[CodPais] [varchar](50) NULL,
	[CodDpto] [varchar](50) NULL,
	[CodMunicipio] [varchar](50) NULL,
	[Sexo] [nchar](10) NULL,
	[esUsuarioInterno] [bit] NULL,
	[esActivo] [bit] NULL,
	[FechaCreacion] [datetime] NOT NULL,
	[FechaModificacion] [datetime] NULL,
	[Imagen] [varchar](300) NULL,
	[Contraseña] [varchar](50) NULL,
	[ImagenUsuario] [image] NULL,
 CONSTRAINT [PK_ART_USUARIO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/* TABLA ROLES*/
CREATE TABLE [dbo].[ART_MUSICA_ROL](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [nvarchar](10) NULL,
	[Nombre] [nvarchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
 CONSTRAINT [PK_Rol] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/* TABLA RECURSOS*/

CREATE TABLE [dbo].[ART_MUSICA_RECURSO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [nchar](10) NULL,
	[IdPadre] [int] NULL,
	[Estado] [bit] NULL,
	[Descripcion] [nvarchar](50) NULL,
	[Ruta] [nvarchar](50) NULL,
	[Tipo] [nvarchar](50) NULL,
	[Nombre] [nvarchar](50) NULL,
	[Titulo] [nvarchar](50) NULL,
	[estilo] [nvarchar](50) NULL,
 CONSTRAINT [PK_Recurso] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


/* TABLA ROL RECURSO*/

CREATE TABLE [dbo].[ART_MUSICA_ROL_RECURSO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RolId] [int] NULL,
	[RecId] [int] NULL,
	[esActivo] [bit] NULL,
	[Fecha] [datetime] NULL,
	[NumMenu] [int] NOT NULL,
	[Orden] [int] NULL,
 CONSTRAINT [PK_RolesRecurso] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ART_MUSICA_ROL_RECURSO]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ROL_RECURSO_ART_MUSICA_RECURSO] FOREIGN KEY([RecId])
REFERENCES [dbo].[ART_MUSICA_RECURSO] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ROL_RECURSO] CHECK CONSTRAINT [FK_ART_MUSICA_ROL_RECURSO_ART_MUSICA_RECURSO]
GO

ALTER TABLE [dbo].[ART_MUSICA_ROL_RECURSO]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ROL_RECURSO_ART_MUSICA_ROL] FOREIGN KEY([RolId])
REFERENCES [dbo].[ART_MUSICA_ROL] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ROL_RECURSO] CHECK CONSTRAINT [FK_ART_MUSICA_ROL_RECURSO_ART_MUSICA_ROL]
GO


/* TABLA USUARIO ROL*/

CREATE TABLE [dbo].[ART_MUSICA_USUARIO_ROL](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleId] [int] NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_UsuarioRol] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ART_MUSICA_USUARIO_ROL]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_USUARIO_ROL_ART_MUSICA_ROL] FOREIGN KEY([RoleId])
REFERENCES [dbo].[ART_MUSICA_ROL] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_USUARIO_ROL] CHECK CONSTRAINT [FK_ART_MUSICA_USUARIO_ROL_ART_MUSICA_ROL]
GO

ALTER TABLE [dbo].[ART_MUSICA_USUARIO_ROL]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_USUARIO_ROL_ART_MUSICA_USUARIO] FOREIGN KEY([UserId])
REFERENCES [dbo].[ART_MUSICA_USUARIO] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_USUARIO_ROL] CHECK CONSTRAINT [FK_ART_MUSICA_USUARIO_ROL_ART_MUSICA_USUARIO]
GO


/*aGENTES EXPERIENCIA*/

CREATE TABLE [dbo].[ART_MUSICA_AGENTE_EXPERIENCIA](
	[Id] [int] NOT NULL,
	[AgenteId] [int] NOT NULL,
	[Empresa] [varchar](500) NOT NULL,
	[Titulo] [varchar](500) NOT NULL,
	[MesInicio] [int] NOT NULL,
	[AnoInicio] [int] NOT NULL,
	[MesFin] [int] NULL,
	[AnoFin] [int] NULL,
	[Descripcion] [varchar](5000) NULL,
	[TrabajoActual] [bit] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE_EXPERIENCIA]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGENTE_EXPERIENCIA_ART_MUSICA_AGENTE] FOREIGN KEY([AgenteId])
REFERENCES [dbo].[ART_MUSICA_AGENTE] ([ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE_EXPERIENCIA] CHECK CONSTRAINT [FK_ART_MUSICA_AGENTE_EXPERIENCIA_ART_MUSICA_AGENTE]
GO

/* Actualización tabla agentes*/
alter table ART_MUSICA_AGENTE add  FechaCreacion date not null
alter table ART_MUSICA_AGENTE add  FechaActualizacion date not null


/* TABLA ESTADOS*/

CREATE TABLE [dbo].[ART_MUSICA_ESTADOS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_ESTADOS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


CREATE TABLE [dbo].[ART_MUSICA_AGENTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IdADM_ART_USUARIO] [int] NOT NULL,
	[PrimerNombre] [varchar](50) NOT NULL,
	[SegundoNombre] [varchar](50) NULL,
	[PrimerApellido] [varchar](50) NOT NULL,
	[SedundoApellido] [varchar](50) NULL,
	[Imagen] [image] NULL,
	[CodTipoDocumento] [int] NOT NULL,
	[Identificacion] [varchar](20) NOT NULL,
	[FechaNacimiento] [date] NULL,
	[Sexo] [nchar](10) NULL,
	[CodPais] [varchar](50) NOT NULL,
	[CodMunicipio] [varchar](5) NULL,
	[OtraCiudad] [varchar](100) NULL,
	[Direccion] [varchar](200) NOT NULL,
	[Telefono] [varchar](50) NULL,
	[LinkPortafolio] [varchar](200) NULL,
	[ARD_ID] [numeric](18, 0) NULL,
	[FechaCreacion] [date] NOT NULL,
	[FechaActualizacion] [date] NOT NULL,
	[EstadoId] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_AGENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGENTE_ART_AREA_ARTISTICAS] FOREIGN KEY([ARD_ID])
REFERENCES [dbo].[ART_AREA_ARTISTICAS] ([ARD_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE] CHECK CONSTRAINT [FK_ART_MUSICA_AGENTE_ART_AREA_ARTISTICAS]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGENTE_ART_MUSICA_ESTADOS] FOREIGN KEY([EstadoId])
REFERENCES [dbo].[ART_MUSICA_ESTADOS] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE] CHECK CONSTRAINT [FK_ART_MUSICA_AGENTE_ART_MUSICA_ESTADOS]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGENTE_ART_MUSICA_USUARIO] FOREIGN KEY([IdADM_ART_USUARIO])
REFERENCES [dbo].[ART_MUSICA_USUARIO] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGENTE] CHECK CONSTRAINT [FK_ART_MUSICA_AGENTE_ART_MUSICA_USUARIO]
GO

/* usuarios ws*/
CREATE TABLE [dbo].[ART_MUSICA_WS_USUARIO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](20) NOT NULL,
	[Contrasena] [varchar](20) NOT NULL,
	[CodigoDepartamento] [varchar](5) NOT NULL,
	[Estado] [bit] NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_WS_USUARIO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ART_MUSICA_WS_USUARIO] ADD  CONSTRAINT [DF_ART_MUSICA_WS_USUARIO_Estado]  DEFAULT ((1)) FOR [Estado]
GO

ALTER TABLE [dbo].[ART_MUSICA_WS_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_WS_USUARIO_ART_MUSICA_WS_USUARIO] FOREIGN KEY([CodigoDepartamento])
REFERENCES [dbo].[BAS_ZONAS_GEOGRAFICAS] ([ZON_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_WS_USUARIO] CHECK CONSTRAINT [FK_ART_MUSICA_WS_USUARIO_ART_MUSICA_WS_USUARIO]
GO