
/****** Object:  StoredProcedure [dbo].[ART_MUSICA_ESCUELAS_Obtener_Todos]    Script Date: 07/12/2015 10:18:37 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[ART_MUSICA_ESCUELAS_Por_UsuarioID] (                  
	@UsuarioId numeric(18,0)           
)AS

SET NOCOUNT ON

SELECT     ART_ENTIDADES_ARTES.ENT_ID, ART_ENTIDADES_ARTES.ENT_NOMBRE, ART_ENTIDADES_ARTES.ENT_IMAGEN, ART_ENTIDADES_ARTES.ENT_ESTADO, 
                      ART_ENTIDADES_ARTES.ENT_NIT, ART_ENTIDADES_ARTES.ENT_NOMBRE_CONTACTO, ART_ENTIDADES_ARTES.ENT_CARGO_CONTACTO, 
                      ART_ENTIDADES_ARTES.ENT_RESENA, ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_TELEFONOS, 
                      ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_CONTACTO_CORREO, ART_ENTIDAD_UBICACION.ZON_ID, BAS_ZONAS_GEOGRAFICAS.ZON_NOMBRE, 
                      BAS_ZONAS_GEOGRAFICAS.ZON_PADRE_ID, dbo.FN_DEPARTAMENTOS(BAS_ZONAS_GEOGRAFICAS.ZON_ID) AS ZON_NOMBRE_PADRE, 
                      ART_ENTIDAD_UBICACION.ENT_DIRECCION, ART_ENTIDAD_UBICACION.ENT_DIRECCION_CORRESPONDENCIA, ART_ENTIDAD_UBICACION.ENT_TELEFONO, 
                      ART_ENTIDAD_UBICACION.ENT_FAX, ART_ENTIDAD_UBICACION.ENT_CORREO_ELECTRONICO_ENTIDAD, ART_ENTIDAD_UBICACION.ENT_PAGINA_WEB, 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.ID_CATEGORIA, ART_MUSICA_ENTIDAD_CATEGORIZACION.FECHA_CATEGORIZACION, 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.PORCENTAJE_TOTAL, ART_MUSICA_CATEGORIA_ESCUELA.DESCRIPCION_CATEGORIA, 
                      ART_MUSICA_ENTIDAD_IDENTIFICACION.USU_ID
FROM         ART_ENTIDADES_ARTES LEFT OUTER JOIN
                      ART_MUSICA_ENTIDAD_CATEGORIZACION ON ART_ENTIDADES_ARTES.ENT_ID = ART_MUSICA_ENTIDAD_CATEGORIZACION.ENT_ID LEFT OUTER JOIN
                      ART_MUSICA_CATEGORIA_ESCUELA ON 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.ID_CATEGORIA = ART_MUSICA_CATEGORIA_ESCUELA.ID_CATEGORIA LEFT OUTER JOIN
                      BAS_ZONAS_GEOGRAFICAS INNER JOIN
                      ART_ENTIDAD_UBICACION ON BAS_ZONAS_GEOGRAFICAS.ZON_ID = ART_ENTIDAD_UBICACION.ZON_ID ON 
                      ART_ENTIDADES_ARTES.ENT_ID = ART_ENTIDAD_UBICACION.ENT_ID LEFT OUTER JOIN
                      ART_MUSICA_ENTIDAD_IDENTIFICACION ON ART_ENTIDADES_ARTES.ENT_ID = ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_ID
WHERE     (ART_ENTIDADES_ARTES.ENT_TIPO = 'E')  AND  ART_MUSICA_ENTIDAD_IDENTIFICACION.USU_ID = @UsuarioId
ORDER BY ART_ENTIDADES_ARTES.ENT_NOMBRE


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[ART_MUSICA_ESCUELAS_Por_EstadoId] (                  
	@EstadoId char          
)AS

SET NOCOUNT ON

SELECT     ART_ENTIDADES_ARTES.ENT_ID, ART_ENTIDADES_ARTES.ENT_NOMBRE, ART_ENTIDADES_ARTES.ENT_IMAGEN, ART_ENTIDADES_ARTES.ENT_ESTADO, 
                      ART_ENTIDADES_ARTES.ENT_NIT, ART_ENTIDADES_ARTES.ENT_NOMBRE_CONTACTO, ART_ENTIDADES_ARTES.ENT_CARGO_CONTACTO, 
                      ART_ENTIDADES_ARTES.ENT_RESENA, ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_TELEFONOS, 
                      ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_CONTACTO_CORREO, ART_ENTIDAD_UBICACION.ZON_ID, BAS_ZONAS_GEOGRAFICAS.ZON_NOMBRE, 
                      BAS_ZONAS_GEOGRAFICAS.ZON_PADRE_ID, dbo.FN_DEPARTAMENTOS(BAS_ZONAS_GEOGRAFICAS.ZON_ID) AS ZON_NOMBRE_PADRE, 
                      ART_ENTIDAD_UBICACION.ENT_DIRECCION, ART_ENTIDAD_UBICACION.ENT_DIRECCION_CORRESPONDENCIA, ART_ENTIDAD_UBICACION.ENT_TELEFONO, 
                      ART_ENTIDAD_UBICACION.ENT_FAX, ART_ENTIDAD_UBICACION.ENT_CORREO_ELECTRONICO_ENTIDAD, ART_ENTIDAD_UBICACION.ENT_PAGINA_WEB, 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.ID_CATEGORIA, ART_MUSICA_ENTIDAD_CATEGORIZACION.FECHA_CATEGORIZACION, 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.PORCENTAJE_TOTAL, ART_MUSICA_CATEGORIA_ESCUELA.DESCRIPCION_CATEGORIA, 
                      ART_MUSICA_ENTIDAD_IDENTIFICACION.USU_ID
FROM         ART_ENTIDADES_ARTES LEFT OUTER JOIN
                      ART_MUSICA_ENTIDAD_CATEGORIZACION ON ART_ENTIDADES_ARTES.ENT_ID = ART_MUSICA_ENTIDAD_CATEGORIZACION.ENT_ID LEFT OUTER JOIN
                      ART_MUSICA_CATEGORIA_ESCUELA ON 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.ID_CATEGORIA = ART_MUSICA_CATEGORIA_ESCUELA.ID_CATEGORIA LEFT OUTER JOIN
                      BAS_ZONAS_GEOGRAFICAS INNER JOIN
                      ART_ENTIDAD_UBICACION ON BAS_ZONAS_GEOGRAFICAS.ZON_ID = ART_ENTIDAD_UBICACION.ZON_ID ON 
                      ART_ENTIDADES_ARTES.ENT_ID = ART_ENTIDAD_UBICACION.ENT_ID LEFT OUTER JOIN
                      ART_MUSICA_ENTIDAD_IDENTIFICACION ON ART_ENTIDADES_ARTES.ENT_ID = ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_ID
WHERE     (ART_ENTIDADES_ARTES.ENT_TIPO = 'E')  AND  ART_ENTIDADES_ARTES.ENT_ESTADO = @EstadoId
ORDER BY ART_ENTIDADES_ARTES.ENT_NOMBRE

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[ART_MUSICA_ESCUELAS_Por_Municipio] (                  
	@UsuarioId int          
)AS

SET NOCOUNT ON

SELECT     ART_ENTIDADES_ARTES.ENT_ID, ART_ENTIDADES_ARTES.ENT_NOMBRE, ART_ENTIDADES_ARTES.ENT_IMAGEN, ART_ENTIDADES_ARTES.ENT_ESTADO, 
                      ART_ENTIDADES_ARTES.ENT_NIT, ART_ENTIDADES_ARTES.ENT_NOMBRE_CONTACTO, ART_ENTIDADES_ARTES.ENT_CARGO_CONTACTO, 
                      ART_ENTIDADES_ARTES.ENT_RESENA, ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_TELEFONOS, 
                      ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_CONTACTO_CORREO, ART_ENTIDAD_UBICACION.ZON_ID, BAS_ZONAS_GEOGRAFICAS.ZON_NOMBRE, 
                      BAS_ZONAS_GEOGRAFICAS.ZON_PADRE_ID, dbo.FN_DEPARTAMENTOS(BAS_ZONAS_GEOGRAFICAS.ZON_ID) AS ZON_NOMBRE_PADRE, 
                      ART_ENTIDAD_UBICACION.ENT_DIRECCION, ART_ENTIDAD_UBICACION.ENT_DIRECCION_CORRESPONDENCIA, ART_ENTIDAD_UBICACION.ENT_TELEFONO, 
                      ART_ENTIDAD_UBICACION.ENT_FAX, ART_ENTIDAD_UBICACION.ENT_CORREO_ELECTRONICO_ENTIDAD, ART_ENTIDAD_UBICACION.ENT_PAGINA_WEB, 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.ID_CATEGORIA, ART_MUSICA_ENTIDAD_CATEGORIZACION.FECHA_CATEGORIZACION, 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.PORCENTAJE_TOTAL, ART_MUSICA_CATEGORIA_ESCUELA.DESCRIPCION_CATEGORIA, 
                      ART_MUSICA_ENTIDAD_IDENTIFICACION.USU_ID
FROM         ART_ENTIDADES_ARTES LEFT OUTER JOIN
                      ART_MUSICA_ENTIDAD_CATEGORIZACION ON ART_ENTIDADES_ARTES.ENT_ID = ART_MUSICA_ENTIDAD_CATEGORIZACION.ENT_ID LEFT OUTER JOIN
                      ART_MUSICA_CATEGORIA_ESCUELA ON 
                      ART_MUSICA_ENTIDAD_CATEGORIZACION.ID_CATEGORIA = ART_MUSICA_CATEGORIA_ESCUELA.ID_CATEGORIA LEFT OUTER JOIN
                      BAS_ZONAS_GEOGRAFICAS INNER JOIN
                      ART_ENTIDAD_UBICACION ON BAS_ZONAS_GEOGRAFICAS.ZON_ID = ART_ENTIDAD_UBICACION.ZON_ID ON 
                      ART_ENTIDADES_ARTES.ENT_ID = ART_ENTIDAD_UBICACION.ENT_ID LEFT OUTER JOIN
                      ART_MUSICA_ENTIDAD_IDENTIFICACION ON ART_ENTIDADES_ARTES.ENT_ID = ART_MUSICA_ENTIDAD_IDENTIFICACION.ENT_ID
					  INNER JOIN ART_MUSICA_USER_CIUDAD C ON ART_ENTIDAD_UBICACION.ZON_ID = C.CodMun
WHERE     (ART_ENTIDADES_ARTES.ENT_TIPO = 'E')  
AND  C.IdUser = @UsuarioId
ORDER BY ART_ENTIDADES_ARTES.ENT_NOMBRE
