USE [SIPA]
GO

/****** Object:  Table [dbo].[ART_MUSICA_FORMULARIO_ARCHIVOS]    Script Date: 09/12/2015 3:57:53 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_FORMULARIO_ARCHIVOS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreArchivo] [varchar](500) NOT NULL,
	[Tipo] [varchar](50) NOT NULL,
	[FRE_ID] [numeric](18, 0) NOT NULL,
	[Archivo] [varbinary](max) NULL,
	[FCO_ID] [numeric](18, 0) NOT NULL,
	[FOR_ID] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_FORMULARIO_ARCHIVOS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ART_MUSICA_FORMULARIO_ARCHIVOS]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_FORMULARIO_ARCHIVOS_ART_ME_FORMULARIOS_REGISTRO] FOREIGN KEY([FRE_ID])
REFERENCES [dbo].[ART_ME_FORMULARIOS_REGISTRO] ([FRE_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_FORMULARIO_ARCHIVOS] CHECK CONSTRAINT [FK_ART_MUSICA_FORMULARIO_ARCHIVOS_ART_ME_FORMULARIOS_REGISTRO]
GO

ALTER TABLE [dbo].[ART_MUSICA_FORMULARIO_ARCHIVOS]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_FORMULARIO_ARCHIVOS_ART_ME_FORMULARIOS_COLUMNAS] FOREIGN KEY([FCO_ID])
REFERENCES [dbo].ART_ME_FORMULARIOS_COLUMNAS ([FCO_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_FORMULARIO_ARCHIVOS] CHECK CONSTRAINT [FK_ART_MUSICA_FORMULARIO_ARCHIVOS_ART_ME_FORMULARIOS_COLUMNAS]
GO

ALTER TABLE [dbo].[ART_MUSICA_FORMULARIO_ARCHIVOS]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_FORMULARIO_ARCHIVOS_ART_ME_FORMULARIOS] FOREIGN KEY([FOR_ID])
REFERENCES [dbo].ART_ME_FORMULARIOS ([FOR_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_FORMULARIO_ARCHIVOS] CHECK CONSTRAINT [FK_ART_MUSICA_FORMULARIO_ARCHIVOS_ART_ME_FORMULARIOS]
GO


update ART_ME_FORMULARIOS set for_perfiles = 'Guardar Visita' where for_id = 1
update ART_ME_FORMULARIOS set for_perfiles = 'Guardar Satisfación' where for_id = 4
update ART_ME_FORMULARIOS set for_perfiles = 'Guardar Materiales' where for_id = 5


-- Author:		Grey Milena Jiménez
-- Create date: Septiembre 10 de 2015
-- Description:	Trae los valores de las columnas de losFormularios dinámicos
-- =============================================
ALTER PROCEDURE [dbo].[ART_ME_ART_MUSICA_FORMULARIOS_VALORES]
	-- Add the parameters for the stored procedure here
	@ENT_ID numeric(18, 0),
	@FormularioId numeric(18, 0)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT ART_ME_FORMULARIOS_VALORES.FVA_ID, 
			ART_ME_FORMULARIOS_VALORES.FVA_VALOR, 
			ART_ME_FORMULARIOS_VALORES.FCO_ID, ART_ME_FORMULARIOS_VALORES.FRE_ID, 
			ART_ME_FORMULARIOS_VALORES.FOR_ID, ART_ME_FORMULARIOS_VALORES.FVA_DUPLICACION, 
			ART_ME_FORMULARIOS_COLUMNAS.FCO_NOMBRE 
From ART_ME_FORMULARIOS_VALORES 
	INNER JOIN ART_ME_FORMULARIOS_COLUMNAS ON ART_ME_FORMULARIOS_VALORES.FCO_ID = ART_ME_FORMULARIOS_COLUMNAS.FCO_ID 
	INNER JOIN ART_ME_FORMULARIOS_REGISTRO ON ART_ME_FORMULARIOS_VALORES.FRE_ID = ART_ME_FORMULARIOS_REGISTRO.FRE_ID
where ART_ME_FORMULARIOS_VALORES.for_id  = @FormularioId
AND ART_ME_FORMULARIOS_REGISTRO.ENT_ID = @ENT_ID
AND ART_ME_FORMULARIOS_REGISTRO.FRE_ID = (SELECT  TOP 1 ART_ME_FORMULARIOS_REGISTRO.FRE_ID 
													 FROM ART_ME_FORMULARIOS_REGISTRO 
													 INNER JOIN ART_ME_FORMULARIOS_VALORES ON ART_ME_FORMULARIOS_REGISTRO.FRE_ID = ART_ME_FORMULARIOS_VALORES.FRE_ID 
													 WHERE ENT_ID = @ENT_ID
													 AND ART_ME_FORMULARIOS_VALORES.FOR_ID = @FormularioId
													 ORDER BY ART_ME_FORMULARIOS_REGISTRO.FRE_FECHA_REGISTRO DESC)
											
END
