USE [SIPA]
GO

/****** Object:  Table [dbo].[ART_MUSICA_TIPO_ENTIDAD]    Script Date: 09/11/2015 4:22:54 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_TIPO_ENTIDAD](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Codigo] [varchar](20) NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_TIPO_ENTIDAD] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


/* CREAR TABLA ENTIDADES MUSICA*/


USE [SIPA]
GO

/****** Object:  Table [dbo].[ART_MUSICA_ENTIDADES]    Script Date: 09/11/2015 4:28:07 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_ENTIDADES](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](200) NOT NULL,
	[Nit] [int] NOT NULL,
	[DigitoVerificacion] [int] NULL,
	[CodigoMunicipio] [varchar](5) NOT NULL,
	[Direccion] [varchar](200) NOT NULL,
	[Telefono] [varchar](50) NOT NULL,
	[Imagen] [image] NULL,
	[CorreoElectronico] [varchar](200) NOT NULL,
	[Latitud] [varchar](20) NULL,
	[Longitud] [varchar](20) NULL,
	[LinkPortafolio] [varchar](200) NULL,
	[ArtMusicaUsuarioId] [int] NOT NULL,
	[EstadoId] [int] NOT NULL,
	[ArdId] [numeric](18, 0) NOT NULL,
	[FechaActualizacion] [date] NOT NULL,
	[FechaCreacion] [date] NOT NULL,
	[Descripcion] [varchar](2000) NULL,
	[TipoEntidadId] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_ENTIDADES] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDADES]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ENTIDADES_ART_AREA_ARTISTICAS] FOREIGN KEY([ArdId])
REFERENCES [dbo].[ART_AREA_ARTISTICAS] ([ARD_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDADES] CHECK CONSTRAINT [FK_ART_MUSICA_ENTIDADES_ART_AREA_ARTISTICAS]
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDADES]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ENTIDADES_ART_MUSICA_ESTADOS] FOREIGN KEY([EstadoId])
REFERENCES [dbo].[ART_MUSICA_ESTADOS] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDADES] CHECK CONSTRAINT [FK_ART_MUSICA_ENTIDADES_ART_MUSICA_ESTADOS]
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDADES]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ENTIDADES_ART_MUSICA_TIPO_ENTIDAD] FOREIGN KEY([TipoEntidadId])
REFERENCES [dbo].[ART_MUSICA_TIPO_ENTIDAD] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDADES] CHECK CONSTRAINT [FK_ART_MUSICA_ENTIDADES_ART_MUSICA_TIPO_ENTIDAD]
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDADES]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ENTIDADES_ART_MUSICA_USUARIO] FOREIGN KEY([ArtMusicaUsuarioId])
REFERENCES [dbo].[ART_MUSICA_USUARIO] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDADES] CHECK CONSTRAINT [FK_ART_MUSICA_ENTIDADES_ART_MUSICA_USUARIO]
GO

/* aGRUPACIONES */


USE [SIPA]
GO

/****** Object:  Table [dbo].[ART_MUSICA_AGRUPACION]    Script Date: 09/11/2015 4:55:16 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ART_MUSICA_AGRUPACION](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](200) NOT NULL,
	[CodigoMunicipio] [varchar](5) NOT NULL,
	[Direccion] [varchar](200) NOT NULL,
	[Telefono] [varchar](50) NOT NULL,
	[Imagen] [image] NULL,
	[CorreoElectronico] [varchar](200) NOT NULL,
	[Latitud] [varchar](20) NULL,
	[Longitud] [varchar](20) NULL,
	[LinkPortafolio] [varchar](200) NULL,
	[ArtMusicaUsuarioId] [int] NOT NULL,
	[EstadoId] [int] NOT NULL,
	[ArdId] [numeric](18, 0) NOT NULL,
	[FechaActualizacion] [date] NOT NULL,
	[FechaCreacion] [date] NOT NULL,
	[Descripcion] [varchar](2000) NULL,
	[CodTipoDocumento] [int] NOT NULL,
	[Identificacion] [varchar](20) NOT NULL,
	[PrimerNombre] [varchar](50) NOT NULL,
	[SegundoNombre] [varchar](50) NULL,
	[PrimerApellido] [varchar](50) NOT NULL,
	[SedundoApellido] [varchar](50) NULL,
	
 CONSTRAINT [PK_ART_MUSICA_AGRUPACION] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_AREA_ARTISTICAS] FOREIGN KEY([ArdId])
REFERENCES [dbo].[ART_AREA_ARTISTICAS] ([ARD_ID])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_AREA_ARTISTICAS]
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_ESTADOS] FOREIGN KEY([EstadoId])
REFERENCES [dbo].[ART_MUSICA_ESTADOS] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_ESTADOS]
GO


ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_USUARIO] FOREIGN KEY([ArtMusicaUsuarioId])
REFERENCES [dbo].[ART_MUSICA_USUARIO] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_AGRUPACION] CHECK CONSTRAINT [FK_ART_MUSICA_AGRUPACION_ART_MUSICA_USUARIO]
GO


CREATE TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOENTIDAD](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TipoEntidadId] [int] NOT NULL,
	[EntidadId] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUSICA_ENTIDAD_TIPOENTIDAD] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOENTIDAD]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ENTIDAD_TIPOENTIDAD_ART_MUSICA_ENTIDADES] FOREIGN KEY([EntidadId])
REFERENCES [dbo].[ART_MUSICA_ENTIDADES] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOENTIDAD] CHECK CONSTRAINT [FK_ART_MUSICA_ENTIDAD_TIPOENTIDAD_ART_MUSICA_ENTIDADES]
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOENTIDAD]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUSICA_ENTIDAD_TIPOENTIDAD_ART_MUSICA_TIPO_ENTIDAD] FOREIGN KEY([TipoEntidadId])
REFERENCES [dbo].[ART_MUSICA_TIPO_ENTIDAD] ([Id])
GO

ALTER TABLE [dbo].[ART_MUSICA_ENTIDAD_TIPOENTIDAD] CHECK CONSTRAINT [FK_ART_MUSICA_ENTIDAD_TIPOENTIDAD_ART_MUSICA_TIPO_ENTIDAD]
GO
