
alter table BAS_TIPOS_DOCUMENTOS_IDENTIDAD add CODIGO VARCHAR(10) NULL
select * from BAS_TIPOS_DOCUMENTOS_IDENTIDAD

INSERT INTO BAS_TIPOS_DOCUMENTOS_IDENTIDAD VALUES ('NUIP', 'S', 'NP')

UPDATE BAS_TIPOS_DOCUMENTOS_IDENTIDAD SET CODIGO = 'CC' WHERE DOC_ID = 2
UPDATE BAS_TIPOS_DOCUMENTOS_IDENTIDAD SET CODIGO = 'NIT' WHERE DOC_ID = 4
UPDATE BAS_TIPOS_DOCUMENTOS_IDENTIDAD SET CODIGO = 'PA' WHERE DOC_ID = 5
UPDATE BAS_TIPOS_DOCUMENTOS_IDENTIDAD SET CODIGO = 'CE' WHERE DOC_ID = 6
UPDATE BAS_TIPOS_DOCUMENTOS_IDENTIDAD SET CODIGO = 'TI' WHERE DOC_ID = 11
UPDATE BAS_TIPOS_DOCUMENTOS_IDENTIDAD SET CODIGO = 'RT' WHERE DOC_ID = 12