SELECT * FROM ART_MUSICA_TIPO_ENTIDAD

INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Formación', 'FO')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Producción', 'PR')
INSERT INTO ART_MUSICA_TIPO_ENTIDAD VALUES ('Creación', 'CO')