--SE CREA NUEVOS CAMPOS EN LA TABLA DE  FORMACION
ALTER TABLE [ART_MUSICA_ENTIDAD_FORMACION] ADD TOTAL_INICACION_POBLACION INT NULL
ALTER TABLE [ART_MUSICA_ENTIDAD_FORMACION] ADD TOTAL_BASICO_POBLACION INT NULL
ALTER TABLE [ART_MUSICA_ENTIDAD_FORMACION] ADD TOTAL_MEDIO_POBLACION INT NULL
ALTER TABLE [ART_MUSICA_ENTIDAD_FORMACION] ADD TOTAL_CURSOS_POBLACION INT NULL
ALTER TABLE [ART_MUSICA_ENTIDAD_FORMACION] ADD TOTAL_PEDAGOGIA_POBLACION INT NULL
ALTER TABLE ART_MUSICA_ENTIDAD_INFRAESTRUCTURA ADD ENT_TIENE_INTERNET BIT NULL
-- SE ACTUALIZA LOS NUEVOS CAMPOS

-- NIVEL INICIO
UPDATE [ART_MUSICA_ENTIDAD_FORMACION] 
SET TOTAL_INICACION_POBLACION = INICIACION_POBLACION_MAYOR_60_ANOS + INICIACION_POBLACION_MENOR_60_ANOS + INICIACION_POBLACION_MENOR_26_ANOS +
INICIACION_POBLACION_MENOR_18_ANOS + INICIACION_POBLACION_MENOR_11_ANOS +  INICIACION_POBLACION_MENOR_6_ANOS

-- NIVEL BASICO
UPDATE [ART_MUSICA_ENTIDAD_FORMACION] 
SET TOTAL_BASICO_POBLACION = BASICO_POBLACION_MAYOR_60_ANOS + BASICO_POBLACION_MENOR_60_ANOS + BASICO_POBLACION_MENOR_26_ANOS +
BASICO_POBLACION_MENOR_18_ANOS + BASICO_POBLACION_MENOR_11_ANOS +  BASICO_POBLACION_MENOR_6_ANOS

--NIVEL MEDIO
UPDATE [ART_MUSICA_ENTIDAD_FORMACION] 
SET TOTAL_MEDIO_POBLACION = MEDIO_POBLACION_MAYOR_60_ANOS + MEDIO_POBLACION_MENOR_60_ANOS + MEDIO_POBLACION_MENOR_26_ANOS +
MEDIO_POBLACION_MENOR_18_ANOS + MEDIO_POBLACION_MENOR_11_ANOS +  MEDIO_POBLACION_MENOR_6_ANOS

--EDUCACION INFORMAL
UPDATE [ART_MUSICA_ENTIDAD_FORMACION] 
SET TOTAL_CURSOS_POBLACION = CURSO_POBLACION_MAYOR_60_ANOS + CURSO_POBLACION_MENOR_60_ANOS + CURSO_POBLACION_MENOR_26_ANOS +
CURSO_POBLACION_MENOR_18_ANOS + CURSO_POBLACION_MENOR_11_ANOS +  CURSO_POBLACION_MENOR_6_ANOS

--PEDAGOGIA
UPDATE [ART_MUSICA_ENTIDAD_FORMACION] 
SET TOTAL_PEDAGOGIA_POBLACION = PEDAGOGIAS_POBLACION_MAYOR_60_ANOS + PEDAGOGIAS_POBLACION_MENOR_60_ANOS + PEDAGOGIAS_POBLACION_MENOR_26_ANOS +
PEDAGOGIAS_POBLACION_MENOR_18_ANOS + PEDAGOGIAS_POBLACION_MENOR_11_ANOS +  PEDAGOGIAS_POBLACION_MENOR_6_ANOS

--- se crea el sp
USE [SIPA]
GO
/****** Object:  StoredProcedure [dbo].[ART_ME_ART_MUSICA_ENTIDAD_FORMACION_ObtenerPorId]    Script Date: 05/08/2015 3:07:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[ART_ME_ART_MUSICA_ENTIDAD_FORMACION_TOTALES] (
	@ENT_ID numeric(18, 0)
)
AS

SET NOCOUNT ON

SELECT
	[ENT_ID],
	[ENT_PROCESOS_FORMACION],
	[ENT_PRACTICAS_MUSICALES_ORIENTADAS_MUSICO],
	[ENT_TALLERES_INDEPENDIENTES],
	[ENT_PROGRAMAS_FORMULADOS_ESCRITO],
	[INICIACION_DURACION_PROMEDIO_MESES],
	TOTAL_INICACION_POBLACION,
	[INICIACION_INTENSIDAD_HORAS_SEMANAL],
	[INICIACION_OBSERVACIONES],
	[BASICO_DURACION_PROMEDIO_MESES],
	TOTAL_BASICO_POBLACION,
	[BASICO_INTENSIDAD_HORAS_SEMANAL],
	[BASICO_OBSERVACIONES],
	[MEDIO_DURACION_PROMEDIO_MESES],
	TOTAL_MEDIO_POBLACION,
	[MEDIO_INTENSIDAD_HORAS_SEMANAL],
	[MEDIO_OBSERVACIONES],
	[CURSO_DURACION_PROCURSO_SEMANA],
	TOTAL_CURSOS_POBLACION,
	[CURSO_INTENSIDAD_HORAS_SEMANAL],
	[CURSO_OBSERVACIONES],
	[PEDAGOGIAS_DURACION_PROPEDAGOGIAS_SEMANA],
	TOTAL_PEDAGOGIA_POBLACION,
	[PEDAGOGIAS_INTENSIDAD_HORAS_SEMANAL],
	[PEDAGOGIAS_OBSERVACIONES]
FROM
	[ART_MUSICA_ENTIDAD_FORMACION]
WHERE
	[ENT_ID] = @ENT_ID


/****** Object:  StoredProcedure [dbo].[ART_ME_ART_MUSICA_ENTIDAD_FORMACION_ObtenerPorId]    Script Date: 05/08/2015 3:07:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ART_ME_ART_MUSICA_ENTIDAD_FORMACION_TOTALES_Actualizar] (
	@ENT_ID numeric(18, 0),
	@ENT_PROCESOS_FORMACION varchar(3000),
	@ENT_PRACTICAS_MUSICALES_ORIENTADAS_MUSICO bit,
	@ENT_TALLERES_INDEPENDIENTES bit,
	@ENT_PROGRAMAS_FORMULADOS_ESCRITO bit,
	@INICIACION_DURACION_PROMEDIO_MESES INT,
	@TOTAL_INICACION_POBLACION INT,
	@INICIACION_INTENSIDAD_HORAS_SEMANAL int,
	@INICIACION_OBSERVACIONES varchar(2000),
	@BASICO_DURACION_PROMEDIO_MESES int,
	@TOTAL_BASICO_POBLACION INT,
	@BASICO_INTENSIDAD_HORAS_SEMANAL int,
	@BASICO_OBSERVACIONES varchar(2000),
	@MEDIO_DURACION_PROMEDIO_MESES int,
	@TOTAL_MEDIO_POBLACION INT,
	@MEDIO_INTENSIDAD_HORAS_SEMANAL int,
	@MEDIO_OBSERVACIONES varchar(2000),
	@CURSO_DURACION_PROCURSO_SEMANA int,
	@TOTAL_CURSOS_POBLACION INT,
	@CURSO_INTENSIDAD_HORAS_SEMANAL int,
	@CURSO_OBSERVACIONES varchar(2000),
	@PEDAGOGIAS_DURACION_PROPEDAGOGIAS_SEMANA int,
	@TOTAL_PEDAGOGIA_POBLACION INT,
	@PEDAGOGIAS_INTENSIDAD_HORAS_SEMANAL int,
	@PEDAGOGIAS_OBSERVACIONES varchar(2000)
)
AS

SET NOCOUNT ON

UPDATE
	[ART_MUSICA_ENTIDAD_FORMACION]
SET
	[ENT_PROCESOS_FORMACION] = @ENT_PROCESOS_FORMACION,
	[ENT_PRACTICAS_MUSICALES_ORIENTADAS_MUSICO] = @ENT_PRACTICAS_MUSICALES_ORIENTADAS_MUSICO,
	[ENT_TALLERES_INDEPENDIENTES] = @ENT_TALLERES_INDEPENDIENTES,
	[ENT_PROGRAMAS_FORMULADOS_ESCRITO] = @ENT_PROGRAMAS_FORMULADOS_ESCRITO,	
	[INICIACION_DURACION_PROMEDIO_MESES] = @INICIACION_DURACION_PROMEDIO_MESES,
	TOTAL_INICACION_POBLACION = @TOTAL_INICACION_POBLACION,
	[INICIACION_INTENSIDAD_HORAS_SEMANAL] = @INICIACION_INTENSIDAD_HORAS_SEMANAL,
	[INICIACION_OBSERVACIONES] = @INICIACION_OBSERVACIONES,
	[BASICO_DURACION_PROMEDIO_MESES] = @BASICO_DURACION_PROMEDIO_MESES,
	TOTAL_BASICO_POBLACION = @TOTAL_BASICO_POBLACION,
	[BASICO_INTENSIDAD_HORAS_SEMANAL] = @BASICO_INTENSIDAD_HORAS_SEMANAL,
	[BASICO_OBSERVACIONES] = @BASICO_OBSERVACIONES,
	[MEDIO_DURACION_PROMEDIO_MESES] = @MEDIO_DURACION_PROMEDIO_MESES,
	TOTAL_MEDIO_POBLACION = @TOTAL_MEDIO_POBLACION,
	[MEDIO_INTENSIDAD_HORAS_SEMANAL] = @MEDIO_INTENSIDAD_HORAS_SEMANAL,
	[MEDIO_OBSERVACIONES] = @MEDIO_OBSERVACIONES,
	[CURSO_DURACION_PROCURSO_SEMANA] = @CURSO_DURACION_PROCURSO_SEMANA,
	TOTAL_CURSOS_POBLACION = @TOTAL_CURSOS_POBLACION,
	[CURSO_INTENSIDAD_HORAS_SEMANAL] = @CURSO_INTENSIDAD_HORAS_SEMANAL,
	[CURSO_OBSERVACIONES] = @CURSO_OBSERVACIONES,
	[PEDAGOGIAS_DURACION_PROPEDAGOGIAS_SEMANA] = @PEDAGOGIAS_DURACION_PROPEDAGOGIAS_SEMANA,
	TOTAL_PEDAGOGIA_POBLACION = @TOTAL_PEDAGOGIA_POBLACION,
	[PEDAGOGIAS_INTENSIDAD_HORAS_SEMANAL] = @PEDAGOGIAS_INTENSIDAD_HORAS_SEMANAL,
	[PEDAGOGIAS_OBSERVACIONES] = @PEDAGOGIAS_OBSERVACIONES
WHERE
	[ENT_ID] = @ENT_ID
